#!/usr/bin/perl
# Copyright (C) 2014  Jesse McGraw (jlmcgraw@gmail.com)

# Process data provided by the FAA
# This current just slurps all of the data into an sqlite database
#
# TODO
# Convert to spatialite
#       ogr2ogr -f SQLite  56daySpatialite.db 56day.db -skip-failures -lco FORMAT=WKT -lco GEOMETRY_NAME=geometry -nlt PROMOTE_TO_MULTI -dsco SPATIALITE=YES -lco SPATIAL_INDEX=YES -lco LAUNDER=NO -gt 65536 --config OGR_SQLITE_SYNCHRONOUS OFF --config OGR_SQLITE_CACHE 128
#
# SELECT load_extension('libspatialite.so');
# SELECT InitSpatialMetadata(1);
#
# UPDATE OBSTACLE_OBSTACLE SET geometry = SetSrid(geometry, 4326);
# SELECT RecoverGeometryColumn('OBSTACLE_OBSTACLE','geometry',4326,'POINT','XY');
#
# UPDATE APT_RWY SET geometry = SetSrid(geometry, 4326);
# SELECT RecoverGeometryColumn('APT_RWY','geometry',4326,'LINESTRING');
# SELECT ASTEXT(geometry) from APT_RWY;
# Expand text
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see [http://www.gnu.org/licenses/].

use 5.010;
use strict;
use warnings;

# use processFaaData;

use File::Basename;
use Getopt::Std;
use Parse::FixedLength;
use Data::Dumper;
$Data::Dumper::Sortkeys = 1;
use DBI;
use processFaaData;
use File::Slurp;
use Params::Validate qw(:all);

use vars qw/ %opt /;

my $opt_string = 've';

my $arg_num = scalar @ARGV;

unless ( getopts( "$opt_string", \%opt ) ) {
    say "Usage: $0 -v -e <data directory>\n";
    say "-v: enable debug output";
    say "-e: expand text";
    exit(1);
}
if ( $arg_num < 1 ) {
    say "Usage: $0 -v -e <data directory>\n";
    say "-v: enable debug output";
    say "-e: expand text";
    exit(1);
}

#Get the target data directory from command line options
my $targetdir = $ARGV[0];

my $debug  = $opt{v};
my $expand = $opt{e};

my %parameters = (
    'autonum' => 'true',
    'trim'    => 'true',
);
my %sections = (
    'APT' => '',
    'ATT' => '',
    'RWY' => '',
    'APT' => '',
    'ARS' => '',
    'RMK' => '',

);

#Have we created table for this recordType
my %haveCreatedTable = ();

#These are parsers for each section/subsection combo we expect to find
#This is really the meat of the whole program
my %hash_of_parsers = (

    # AFF => {
    # 'AFF1' => '
    # RECORD_TYPE_INDICATOR:4
    # AIR_ROUTE_TRAFFIC_CONTROL_CENTER_IDENTIFIER:4
    # AIR_ROUTE_TRAFFIC_CONTROL_CENTER_NAME:40
    # SITE_LOCATION_LOCATION_OF_THE_FACILITY_CONTROLLED_BY_THE_AIR_RO:30
    # CROSS_REFERENCE_ALTERNATE_NAME_FOR_REMOTE_COMMUNICATIONS_AIR_GR:50
    # FACILITY_TYPE:5
    # INFORMATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # SITE_STATE_NAME_EX_NEW_MEXICO:30
    # SITE_STATE_POST_OFFICE_CODE_EX_NM:2
    # SITE_LATITUDE_FORMATTED:14
    # SITE_LATITUDE_SECONDS:11
    # SITE_LONGITUDE_FORMATTED:14
    # SITE_LONGITUDE_SECONDS:11
    # BLANK:29
    # ',
    # 'AFF2' => '
    # RECORD_TYPE_INDICATOR:4
    # AIR_ROUTE_TRAFFIC_CONTROL_CENTER_IDENTIFIER:4
    # SITE_LOCATION_LOCATION_OF_THE_FACILITY_CONTROLLED_BY_THE_AIR_RO:30
    # FACILITY_TYPE:5
    # SITE_REMARKS_ELEMENT_NUMBER:4
    # SITE_REMARKS_TEXT:200
    # BLANK:7
    # ',
    # 'AFF3' => '
    # RECORD_TYPE_INDICATOR:4
    # AIR_ROUTE_TRAFFIC_CONTROL_CENTER_IDENTIFIER:4
    # SITE_LOCATION_LOCATION_OF_THE_FACILITY_CONTROLLED_BY_THE_AIR_RO:30
    # FACILITY_TYPE:5
    # FREQUENCY_ASSOCIATED_WITH_THE_FACILITY:8
    # ALTITUDE_INDICATION_OF_WHETHER_LOW_HIGH_LOW_HIGH_AND_OR_ULTRA_H:10
    # SPECIAL_USAGE_NAME_SPECIAL_USAGE_NAME_FOR_EACH_FREQUENCY:17
    # LOCATION_IDENTIFIER_ASSIGNED_TO_THE_LANDING_FACILITY_AIRPORT:4
    # ASSOCIATED_STATE_NAME:30
    # ASSOCIATED_STATE_POST_OFFICE_CODE:2
    # ASSOCIATED_CITY_NAME:40
    # OFFICIAL_AIRPORT_NAME:50
    # LATITUDE_OF_THE_AIRPORT_FORMATTED:14
    # LATITUDE_OF_THE_AIRPORT_SECONDS:11
    # LONGITUDE_OF_THE_AIRPORT_FORMATTED:14
    # LONGITUDE_OF_THE_AIRPORT_SECONDS:11
    # ',
    # 'AFF4' => '
    # RECORD_TYPE_INDICATOR:4
    # AIR_ROUTE_TRAFFIC_CONTROL_CENTER_IDENTIFIER:4
    # SITE_LOCATION_LOCATION_OF_THE_FACILITY_CONTROLLED_BY_THE_AIR_RO:30
    # FACILITY_TYPE:5
    # FREQUENCY_ASSOCIATED_WITH_THE_REMARK:8
    # FREQUENCY_REMARK_SEQUENCE_NUMBER:2
    # FREQUENCY_REMARKS_TEXT:200
    # BLANK:1
    # '
    # },
    # ANR => {
    # 'ANR1' => '
    # RECORD_TYPE_INDICATOR:4
    # ORIGIN_FACILITY_LOCATION_IDENTIFIER:5
    # DESTINATION_FACILITY_LOCATION_IDENTIFIER:5
    # TYPE_OF_ROUTE_CODE_ANR:3
    # ROUTE_IDENTIFIER_SEQUENCE_NUMBER_1_99:2
    # TYPE_OF_ROUTE_DESCRIPTION_ADVANCED_NAV_ROUTE:30
    # ADVANCED_NAV_ROUTE_AREA_DESCRIPTION:75
    # ADVANCED_NAV_ROUTE_ALTITUDE_DESCRIPTION:40
    # AIRCRAFT_ALLOWED_LIMITATIONS_DESCRIPTION:35
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_1:15
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_2:15
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_3:15
    # ROUTE_DIRECTION_LIMITATIONS_DESCRIPTION:20
    # ',
    # 'ANR2' => '
    # RECORD_TYPE_INDICATOR:4
    # ORIGIN_FACILITY_LOCATION_IDENTIFIER:5
    # DESTINATION_FACILITY_LOCATION_IDENTIFIER:5
    # TYPE_OF_ROUTE_CODE_ANR:3
    # ROUTE_IDENTIFIER_SEQUENCE_NUMBER_1_99:2
    # SEGMENT_SEQUENCE_NUMBER_WITHIN_THE_ROUTE:3
    # SEGMENT_IDENTIFIER_NAVAID_IDENT_AWY_NUMBER_FIX_NAME_SID_NAME_ST:15
    # SEGMENT_TYPE_DESCRIBED:7
    # FIX_STATE_CODE_POST_OFFICE_ALPHA_CODE:2
    # ICAO_REGION_CODE_FOR_FIX:2
    # NAVAID_FACILITY_TYPE_CODE:2
    # ',
    # },
    APT => {
    'ATT' => '
    RECORD_TYPE_INDICATOR:3
    LANDING_FACILITY_SITE_NUMBER:11
    LANDING_FACILITY_STATE_POST_OFFICE_CODE:2
    ATTENDANCE_SCHEDULE_SEQUENCE_NUMBER:2
    AIRPORT_ATTENDANCE_SCHEDULE:108
    ATTENDANCE_SCHEDULE_RECORD_FILLER:1403
    ',

    'APT' => '
    RECORD_TYPE_INDICATOR:3
    LANDING_FACILITY_SITE_NUMBER:11
    LANDING_FACILITY_TYPE:13
    LOCATION_IDENTIFIER:4
    INFORMATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    FAA_REGION_CODE:3
    FAA_DISTRICT_OR_FIELD_OFFICE_CODE:4
    ASSOCIATED_STATE_POST_OFFICE_CODE:2
    ASSOCIATED_STATE_NAME:20
    ASSOCIATED_COUNTY_OR_PARISH_NAME:21
    ASSOCIATED_COUNTY_S_STATE_POST_OFFICE_CODE:2
    ASSOCIATED_CITY_NAME:40
    OFFICIAL_FACILITY_NAME:50
    AIRPORT_OWNERSHIP_TYPE:2
    FACILITY_USE:2
    FACILITY_OWNER_S_NAME:35
    OWNER_S_ADDRESS:72
    OWNER_S_CITY_STATE_AND_ZIP_CODE:45
    OWNER_S_PHONE_NUMBER:16
    FACILITY_MANAGER_S_NAME:35
    MANAGER_S_ADDRESS:72
    MANAGER_S_CITY_STATE_AND_ZIP_CODE:45
    MANAGER_S_PHONE_NUMBER:16
    AIRPORT_REFERENCE_POINT_LATITUDE_FORMATTED:15
    AIRPORT_REFERENCE_POINT_LATITUDE_SECONDS:12
    AIRPORT_REFERENCE_POINT_LONGITUDE_FORMATTED:15
    AIRPORT_REFERENCE_POINT_LONGITUDE_SECONDS:12
    AIRPORT_REFERENCE_POINT_DETERMINATION_METHOD:1
    AIRPORT_ELEVATION_NEAREST_TENTH_OF_A_FOOT_MSL:7
    AIRPORT_ELEVATION_DETERMINATION_METHOD:1
    MAGNETIC_VARIATION_AND_DIRECTION:3
    MAGNETIC_VARIATION_EPOCH_YEAR:4
    TRAFFIC_PATTERN_ALTITUDE_WHOLE_FEET_AGL:4
    AERONAUTICAL_SECTIONAL_CHART_ON_WHICH_FACILITY_APPEARS:30
    DISTANCE_FROM_CENTRAL_BUSINESS_DISTRICT_OF_THE_ASSOCIATED_CITY_TO_THE_AIRPORT:2
    DIRECTION_OF_AIRPORT_FROM_CENTRAL_BUSINESS_DISTRICT_OF_ASSOCIATED_CITY:3
    LAND_AREA_COVERED_BY_AIRPORT_ACRES:5
    BOUNDARY_ARTCC_IDENTIFIER:4
    BOUNDARY_ARTCC_FAA_COMPUTER_IDENTIFIER:3
    BOUNDARY_ARTCC_NAME:30
    RESPONSIBLE_ARTCC_IDENTIFIER:4
    RESPONSIBLE_ARTCC_FAA_COMPUTER_IDENTIFIER:3
    RESPONSIBLE_ARTCC_NAME:30
    TIE_IN_FSS_PHYSICALLY_LOCATED_ON_FACILITY:1
    TIE_IN_FLIGHT_SERVICE_STATION_FSS_IDENTIFIER:4
    TIE_IN_FSS_NAME:30
    LOCAL_PHONE_NUMBER_FROM_AIRPORT_TO_FSS_FOR_ADMINISTRATIVE_SERVICES:16
    TOLL_FREE_PHONE_NUMBER_FROM_AIRPORT_TO_FSS_FOR_PILOT_BRIEFING_SERVICES:16
    ALTERNATE_FSS_IDENTIFIER:4
    ALTERNATE_FSS_NAME:30
    TOLL_FREE_PHONE_NUMBER_FROM_AIRPORT_TO_ALTERNATE_FSS_FOR_PILOT_BRIEFING_SERVICES:16
    IDENTIFIER_OF_THE_FACILITY_RESPONSIBLE_FOR_ISSUING_NOTICES_TO_AIRMEN_NOTAMS_AND_WEATHER_INFORMATION_FOR_THE_AIRPORT:4
    AVAILABILITY_OF_NOTAM_D_SERVICE_AT_AIRPORT:1
    AIRPORT_ACTIVATION_DATE_MM_YYYY:7
    AIRPORT_STATUS_CODE:2
    AIRPORT_ARFF_CERTIFICATION_TYPE_AND_DATE:15
    NPIAS_FEDERAL_AGREEMENTS_CODE:7
    AIRPORT_AIRSPACE_ANALYSIS_DETERMINATION:13
    FACILITY_HAS_BEEN_DESIGNATED_BY_THE_U_S_TREASURY_AS_AN_INTERNATIONAL_AIRPORT_OF_ENTRY_FOR_CUSTOMS:1
    FACILITY_HAS_BEEN_DESIGNATED_BY_THE_U_S_TREASURY_AS_A_CUSTOMS_LANDING_RIGHTS_AIRPORT:1
    FACILITY_HAS_MILITARY_CIVIL_JOINT_USE_AGREEMENT:1
    AIRPORT_HAS_ENTERED_INTO_AN_AGREEMENT_THAT_GRANTS_LANDING_RIGHTS_TO_THE_MILITARY:1
    AIRPORT_INSPECTION_METHOD:2
    AGENCY_GROUP_PERFORMING_PHYSICAL_INSPECTION:1
    LAST_PHYSICAL_INSPECTION_DATE_MMDDYYYY:8
    LAST_DATE_INFORMATION_REQUEST_WAS_COMPLETED_BY_FACILITY_OWNER_OR_MANAGER_MMDDYYYY:8
    FUEL_TYPES_AVAILABLE_FOR_PUBLIC_USE_AT_THE_AIRPORT:40
    AIRFRAME_REPAIR_SERVICE_AVAILABILITY_TYPE:5
    POWER_PLANT_ENGINE_REPAIR_AVAILABILITY_TYPE:5
    TYPE_OF_BOTTLED_OXYGEN_AVAILABLE:8
    TYPE_OF_BULK_OXYGEN_AVAILABLE:8
    AIRPORT_LIGHTING_SCHEDULE:7
    BEACON_LIGHTING_SCHEDULE:7
    AIR_TRAFFIC_CONTROL_TOWER_LOCATED_ON_AIRPORT:1
    UNICOM_FREQUENCY_AVAILABLE_AT_THE_AIRPORT:7
    COMMON_TRAFFIC_ADVISORY_FREQUENCY_CTAF:7
    SEGMENTED_CIRCLE_AIRPORT_MARKER_SYSTEM_ON_THE_AIRPORT:4
    LENS_COLOR_OF_OPERABLE_BEACON_LOCATED_ON_THE_AIRPORT:3
    LANDING_FEE_CHARGED_TO_NON_COMMERCIAL_USERS_OF_AIRPORT:1
    LANDING_FACILITY_IS_USED_FOR_MEDICAL_PURPOSES:1
    SINGLE_ENGINE_GENERAL_AVIATION_AIRCRAFT:3
    MULTI_ENGINE_GENERAL_AVIATION_AIRCRAFT:3
    JET_ENGINE_GENERAL_AVIATION_AIRCRAFT:3
    GENERAL_AVIATION_HELICOPTER:3
    OPERATIONAL_GLIDERS:3
    OPERATIONAL_MILITARY_AIRCRAFT_INCLUDING_HELICOPTERS:3
    ULTRALIGHT_AIRCRAFT:3
    COMMERCIAL_SERVICES:6
    COMMUTER_SERVICES:6
    AIR_TAXI:6
    GENERAL_AVIATION_LOCAL_OPERATIONS:6
    GENERAL_AVIATION_ITINERANT_OPERATIONS:6
    MILITARY_AIRCRAFT_OPERATIONS:6
    ENDING_DATE_ON_WHICH_ANNUAL_OPERATIONS_DATA_IS_BASED_MM_DD_YYYY:10
    AIRPORT_POSITION_SOURCE:16
    AIRPORT_POSITION_SOURCE_DATE_MM_DD_YYYY:10
    AIRPORT_ELEVATION_SOURCE:16
    AIRPORT_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    CONTRACT_FUEL_AVAILABLE:1
    TRANSIENT_STORAGE_FACILITIES:12
    OTHER_AIRPORT_SERVICES_AVAILABLE:71
    WIND_INDICATOR:3
    ICAO_IDENTIFIER:7
    AIRPORT_RECORD_FILLER_BLANK:312
    ',
    'RWY' => '
    RECORD_TYPE_INDICATOR:3
    LANDING_FACILITY_SITE_NUMBER:11
    RUNWAY_STATE_POST_OFFICE_CODE:2
    RUNWAY_IDENTIFICATION:7
    PHYSICAL_RUNWAY_LENGTH_NEAREST_FOOT:5
    PHYSICAL_RUNWAY_WIDTH_NEAREST_FOOT:4
    RUNWAY_SURFACE_TYPE_AND_CONDITION:12
    RUNWAY_SURFACE_TREATMENT:5
    PAVEMENT_CLASSIFICATION_NUMBER_PCN:11
    RUNWAY_LIGHTS_EDGE_INTENSITY:5
    BASE_END_IDENTIFIER:3
    BASE_RUNWAY_END_TRUE_ALIGNMENT:3
    BASE_INSTRUMENT_LANDING_SYSTEM_ILS_TYPE:10
    BASE_RIGHT_HAND_TRAFFIC_PATTERN_FOR_LANDING_AIRCRAFT:1
    BASE_RUNWAY_MARKINGS_TYPE:5
    BASE_RUNWAY_MARKINGS_CONDITION:1
    BASE_LATITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED:15
    BASE_LATITUDE_OF_PHYSICAL_RUNWAY_END_SECONDS:12
    BASE_LONGITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED:15
    BASE_LONGITUDE_OF_PHYSICAL_RUNWAY_END_SECONDS:12
    BASE_ELEVATION_FEET_MSL_AT_PHYSICAL_RUNWAY_END:7
    BASE_THRESHOLD_CROSSING_HEIGHT_FEET_AGL:3
    BASE_VISUAL_GLIDE_PATH_ANGLE_HUNDREDTHS_OF_DEGREES:4
    BASE_LATITUDE_AT_DISPLACED_THRESHOLD_FORMATTED:15
    BASE_LATITUDE_AT_DISPLACED_THRESHOLD_SECONDS:12
    BASE_LONGITUDE_AT_DISPLACED_THRESHOLD_FORMATTED:15
    BASE_LONGITUDE_AT_DISPLACED_THRESHOLD_SECONDS:12
    BASE_ELEVATION_AT_DISPLACED_THRESHOLD_FEET_MSL:7
    BASE_DISPLACED_THRESHOLD___LENGTH_IN_FEET_FROM_RUNWAY_END:4
    BASE_ELEVATION_AT_TOUCHDOWN_ZONE_FEET_MSL:7
    BASE_VISUAL_GLIDE_SLOPE_INDICATORS:5
    BASE_RUNWAY_VISUAL_RANGE_EQUIPMENT_RVR:3
    BASE_RUNWAY_VISIBILITY_VALUE_EQUIPMENT_RVV:1
    BASE_APPROACH_LIGHT_SYSTEM:8
    BASE_RUNWAY_END_IDENTIFIER_LIGHTS_REIL_AVAILABILITY:1
    BASE_RUNWAY_CENTERLINE_LIGHTS_AVAILABILITY:1
    BASE_RUNWAY_END_TOUCHDOWN_LIGHTS_AVAILABILITY:1
    BASE_CONTROLLING_OBJECT_DESCRIPTION:11
    BASE_CONTROLLING_OBJECT_MARKED_LIGHTED:4
    BASE_FAA_CFR_PART_77_OBJECTS_AFFECTING_NAVIGABLE_AIRSPACE_RUNWAY_CATEGORY:5
    BASE_CONTROLLING_OBJECT_CLEARANCE_SLOPE:2
    BASE_CONTROLLING_OBJECT_HEIGHT_ABOVE_RUNWAY:5
    BASE_CONTROLLING_OBJECT_DISTANCE_FROM_RUNWAY_END:5
    BASE_CONTROLLING_OBJECT_CENTERLINE_OFFSET:7
    RECIPROCAL_END_IDENTIFIER:3
    RECIPROCAL_RUNWAY_END_TRUE_ALIGNMENT:3
    RECIPROCAL_INSTRUMENT_LANDING_SYSTEM_ILS_TYPE:10
    RECIPROCAL_RIGHT_HAND_TRAFFIC_PATTERN_FOR_LANDING_AIRCRAFT:1
    RECIPROCAL_RUNWAY_MARKINGS_TYPE:5
    RECIPROCAL_RUNWAY_MARKINGS_CONDITION:1
    RECIPROCAL_LATITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED:15
    RECIPROCAL_LATITUDE_OF_PHYSICAL_RUNWAY_END_SECONDS:12
    RECIPROCAL_LONGITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED:15
    RECIPROCAL_LONGITUDE_OF_PHYSICAL_RUNWAY_END_SECONDS:12
    RECIPROCAL_ELEVATION_FEET_MSL_AT_PHYSICAL_RUNWAY_END:7
    RECIPROCAL_THRESHOLD_CROSSING_HEIGHT_FEET_AGL:3
    RECIPROCAL_VISUAL_GLIDE_PATH_ANGLE_HUNDREDTHS_OF_DEGREES:4
    RECIPROCAL_LATITUDE_AT_DISPLACED_THRESHOLD_FORMATTED:15
    RECIPROCAL_LATITUDE_AT_DISPLACED_THRESHOLD_SECONDS:12
    RECIPROCAL_LONGITUDE_AT_DISPLACED_THRESHOLD_FORMATTED:15
    RECIPROCAL_LONGITUDE_AT_DISPLACED_THRESHOLD_SECONDS:12
    RECIPROCAL_ELEVATION_AT_DISPLACED_THRESHOLD_FEET_MSL:7
    RECIPROCAL_DISPLACED_THRESHOLD___LENGTH_IN_FEET_FROM_RUNWAY_END:4
    RECIPROCAL_ELEVATION_AT_TOUCHDOWN_ZONE_FEET_MSL:7
    RECIPROCAL_APPROACH_SLOPE_INDICATOR_EQUIPMENT:5
    RECIPROCAL_RUNWAY_VISUAL_RANGE_EQUIPMENT_RVR:3
    RECIPROCAL_RUNWAY_VISIBILITY_VALUE_EQUIPMENT_RVV:1
    RECIPROCAL_APPROACH_LIGHT_SYSTEM:8
    RECIPROCAL_RUNWAY_END_IDENTIFIER_LIGHTS_REIL_AVAILABILITY:1
    RECIPROCAL_RUNWAY_CENTERLINE_LIGHTS_AVAILABILITY:1
    RECIPROCAL_RUNWAY_END_TOUCHDOWN_LIGHTS_AVAILABILITY:1
    RECIPROCAL_CONTROLLING_OBJECT_DESCRIPTION:11
    RECIPROCAL_CONTROLLING_OBJECT_MARKED_LIGHTED:4
    RECIPROCAL_FAA_CFR_PART_77_OBJECTS_AFFECTING_NAVIGABLE_AIRSPACE_RUNWAY_CATEGORY:5
    RECIPROCAL_CONTROLLING_OBJECT_CLEARANCE_SLOPE:2
    RECIPROCAL_CONTROLLING_OBJECT_HEIGHT_ABOVE_RUNWAY:5
    RECIPROCAL_CONTROLLING_OBJECT_DISTANCE_FROM_RUNWAY_END:5
    RECIPROCAL_CONTROLLING_OBJECT_CENTERLINE_OFFSET:7
    RUNWAY_LENGTH_SOURCE:16
    RUNWAY_LENGTH_SOURCE_DATE_MM_DD_YYYY:10
    RUNWAY_WEIGHT_BEARING_CAPACITY_FOR_Single_wheel:6
    RUNWAY_WEIGHT_BEARING_CAPACITY_FOR_Dual_wheel:6
    RUNWAY_WEIGHT_BEARING_CAPACITY_FOR_Two_dual_wheels_in_tandem:6
    RUNWAY_WEIGHT_BEARING_CAPACITY_FOR_Two_dual_wheels_in_double_tandem:6
    BASE_RUNWAY_END_GRADIENT:5
    BASE_RUNWAY_END_GRADIENT_DIRECTION_UP_OR_DOWN:4
    BASE_RUNWAY_END_POSITION_SOURCE:16
    BASE_RUNWAY_END_POSITION_SOURCE_DATE_MM_DD_YYYY:10
    BASE_RUNWAY_END_ELEVATION_SOURCE:16
    BASE_RUNWAY_END_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    BASE_DISPLACED_THESHOLD_POSITION_SOURCE:16
    BASE_DISPLACED_THESHOLD_POSITION_SOURCE_DATE_MM_DD_YYYY:10
    BASE_DISPLACED_THESHOLD_ELEVATION_SOURCE:16
    BASE_DISPLACED_THESHOLD_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    BASE_TOUCHDOWN_ZONE_ELEVATION_SOURCE:16
    BASE_TOUCHDOWN_ZONE_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    BASE_TAKEOFF_RUN_AVAILABLE_TORA_IN_FEET:5
    BASE_TAKEOFF_DISTANCE_AVAILABLE_TODA_IN_FEET:5
    BASE_ACLT_STOP_DISTANCE_AVAILABLE_ASDA_IN_FEET:5
    BASE_LANDING_DISTANCE_AVAILABLE_LDA_IN_FEET:5
    BASE_AVAILABLE_LANDING_DISTANCE_FOR_LAND_AND_HOLD_SHORT_OPERATIONS_LAHSO:5
    BASE_ID_OF_INTERSECTING_RUNWAY_DEFINING_HOLD_SHORT_POINT:7
    BASE_DESCRIPTION_OF_ENTITY_DEFINING_HOLD_SHORT_POINT:40
    BASE_LATITUDE_OF_LAHSO_HOLD_SHORT_POINT_FORMATTED:15
    BASE_LATITUDE_OF_LAHSO_HOLD_SHORT_POINT_SECONDS:12
    BASE_LONGITUDE_OF_LAHSO_HOLD_SHORT_POINT_FORMATTED:15
    BASE_LONGITUDE_OF_LAHSO_HOLD_SHORT_POINT_SECONDS:12
    BASE_LAHSO_HOLD_SHORT_POINT_LAT_LONG_SOURCE:16
    BASE_HOLD_SHORT_POINT_LAT_LONG_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_RUNWAY_END_GRADIENT:5
    RECIPROCAL_RUNWAY_END_GRADIENT_DIRECTION_UP_OR_DOWN:4
    RECIPROCAL_RUNWAY_END_POSITION_SOURCE:16
    RECIPROCAL_RUNWAY_END_POSITION_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_RUNWAY_END_ELEVATION_SOURCE:16
    RECIPROCAL_RUNWAY_END_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_DISPLACED_THESHOLD_POSITION_SOURCE:16
    RECIPROCAL_DISPLACED_THESHOLD_POSITION_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_DISPLACED_THESHOLD_ELEVATION_SOURCE:16
    RECIPROCAL_DISPLACED_THESHOLD_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_TOUCHDOWN_ZONE_ELEVATION_SOURCE:16
    RECIPROCAL_TOUCHDOWN_ZONE_ELEVATION_SOURCE_DATE_MM_DD_YYYY:10
    RECIPROCAL_TAKEOFF_RUN_AVAILABLE_TORA_IN_FEET:5
    RECIPROCAL_TAKEOFF_DISTANCE_AVAILABLE_TODA_IN_FEET:5
    RECIPROCAL_ACLT_STOP_DISTANCE_AVAILABLE_ASDA_IN_FEET:5
    RECIPROCAL_LANDING_DISTANCE_AVAILABLE_LDA_IN_FEET:5
    RECIPROCAL_AVAILABLE_LANDING_DISTANCE_FOR_LAND_AND_HOLD_SHORT_OPERATIONS_LAHSO:5
    RECIPROCAL_ID_OF_INTERSECTING_RUNWAY_DEFINING_HOLD_SHORT_POINT:7
    RECIPROCAL_DESCRIPTION_OF_ENTITY_DEFINING_HOLD_SHORT_POINT:40
    RECIPROCAL_LATITUDE_OF_LAHSO_HOLD_SHORT_POINT_FORMATTED:15
    RECIPROCAL_LATITUDE_OF_LAHSO_HOLD_SHORT_POINT_SECONDS:12
    RECIPROCAL_LONGITUDE_OF_LAHSO_HOLD_SHORT_POINT_FORMATTED:15
    RECIPROCAL_LONGITUDE_OF_LAHSO_HOLD_SHORT_POINT_SECONDS:12
    RECIPROCAL_LAHSO_HOLD_SHORT_POINT_LAT_LONG_SOURCE:16
    RECIPROCAL_HOLD_SHORT_POINT_LAT_LONG_SOURCE_DATE_MM_DD_YYYY:10
    RUNWAY_RECORD_FILLER_BLANK:388
    ',

    'ARS' => '
    RECORD_TYPE_INDICATOR:3
    LANDING_FACILITY_SITE_NUMBER:11
    LANDING_FACILITY_STATE_POST_OFFICE_CODE:2
    RUNWAY_IDENTIFICATION:7
    RUNWAY_END_IDENTIFIER:3
    TYPE_OF_AIRCRAFT_ARRESTING_DEVICE:9
    ARRESTING_SYSTEM_RECORD_FILLER_BLANK:1494
    ',
    'RMK' => '
    RECORD_TYPE_INDICATOR:3
    LANDING_FACILITY_SITE_NUMBER:11
    LANDING_FACILITY_STATE_POST_OFFICE_CODE:2
    REMARK_ELEMENT_NAME:13
    REMARK_TEXT:1500
    '
    },
    # ARB => {
    # 'ARB' => '
    # RECORD_IDENTIFIER_ARTCC_IDENTIFIER_ALTITUDE_STRUCTURE_CODE_FIVE:12
    # CENTER_NAME:40
    # ALTITUDE_STRUCTURE_DECODE_NAME:10
    # LATITUDE_OF_THE_BOUNDARY_POINT:14
    # LONGITUDE_OF_THE_BOUNDARY_POINT:14
    # DESCRIPTION_OF_BOUNDARY_LINE_CONNECTING_POINTS_ON_THE_BOUNDARY:300
    # SIX_DIGIT_NUMBER_USED_TO_MAINTAIN_PROPER_SEQUENCE_OF_BOUNDARY_S:6
    # AN_X_IN_THIS_FIELD_INDICATES_THIS_POINT_IS_USED_ONLY_IN_THE_NAS:1
    # '
    # },
    # ATS => {
    # 'ATS1' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # CHART_PUBLICATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # TRACK_ANGLE_OUTBOUND_RNAV_FORMAT_NNN_NNN:7
    # DISTANCE_TO_CHANGEOVER_POINT_RNAV_FORMAT_NNNNN:5
    # TRACK_ANGLE_INBOUND_RNAV_FORMAT_NNN_NNN:7
    # DISTANCE_TO_NEXT_POINT_IN_NAUTICAL_MILES_FORMAT_NNN_NN:6
    # BEARING_RESERVED_PRESENTLY_000_00_ENTERED_FORMAT_NNN_NN_OR_BLAN:6
    # SEGMENT_MAGNETIC_COURSE_FORMAT_NNN_NN_OR_BLANKS:6
    # SEGMENT_MAGNETIC_COURSE_OPPOSITE_DIRECTION_FORMAT_NNN_NN_OR_BLA:6
    # DISTANCE_TO_NEXT_POINT_IN_SEGMENT_IN_NAUTICAL_MILES_FORMAT_NNN:6
    # POINT_TO_POINT_MINIMUM_ENROUTE_ALTITUDE_MEA_FORMAT_NNNNN:5
    # POINT_TO_POINT_MINIMUM_ENROUTE_DIRECTION_MEA_FORMAT_AAAAAAA:7
    # POINT_TO_POINT_MINIMUM_ENROUTE_ALTITUDE_MEA_OPPOSITE_DIRECTION:5
    # POINT_TO_POINT_MINIMUM_ENROUTE_DIRECTION_MEA_OPPOSITE_DIRECTION:7
    # POINT_TO_POINT_MAXIMUM_AUTHORIZED_ALTITUDE:5
    # POINT_TO_POINT_MINIMUM_OBSTRUCTION_CLEARANCE_ALTITUDE_MOCA:5
    # AIRWAY_GAP_FLAG_INDICATOR_X_ENTERED_WHEN_AIRWAY_DISCONTINUED:1
    # DISTANCE_FROM_THIS_POINT_TO_THE_CHANGEOVER_POINT_FOR_THE_NEXT_N:3
    # MINIMUM_CROSSING_ALTITUDE_FORMAT_NNNNN:5
    # DIRECTION_OF_CROSSING_FORMAT_AAAAAAA:7
    # MINIMUM_CROSSING_ALTITUDE_OPPOSITE_DIRECTION_FORMAT_NNNNN:5
    # DIRECTION_OF_CROSSING_OPPOSITE_DIRECTION_FORMAT_AAAAAAA:7
    # GAP_IN_SIGNAL_COVERAGE_INDICATOR:1
    # U_S_AIRSPACE_ONLY_INDICATOR:1
    # NAVAID_MAGNETIC_VARIATION:5
    # NAVAID_FIX_ARTCC:3
    # RESERVED_TO_POINT_PART95:40
    # RESERVED_NEXT_MEA_POINT_PART95:50
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:5
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:7
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:5
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:7
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'ATS2' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # ATS_AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # NAVAID_FACILITY_FIX_NAME:40
    # NAVAID_FACILITY_FIX_TYPE:25
    # FIX_TYPE_PUBLICATION_CATEGORY:15
    # NAVAID_FACILITY_FIX_STATE_P_O_CODE:2
    # ICAO_REGION_CODE_For_FIX:2
    # NAVAID_FACILITY_FIX_LATITUDE:14
    # NAVAID_FACILITY_FIX_LONGITUDE:14
    # FIX_MINIMUM_RECEPTION_ALTITUDE_MRA_FORMAT_NNNNN_OR_BLANKS:5
    # NAVAID_IDENTIFIER:4
    # RESERVED_FROM_POINT_PART95:57
    # BLANKS:67
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'ATS3' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # ATS_AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # NAVAID_FACILITY_NAME:30
    # NAVAID_FACILITY_TYPE:25
    # NAVAID_FACILITY_STATE_P_O_CODE:2
    # NAVAID_FACILITY_LATITUDE:14
    # NAVAID_FACILITY_LONGITUDE:14
    # BLANKS:160
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'ATS4' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # ATS_AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # REMARKS_TEXT:200
    # BLANKS:45
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'ATS5' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # REMARKS_TEXT:200
    # BLANKS:45
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'RMK' => '
    # RECORD_TYPE_INDICATOR:4
    # ATS_AIRWAY_DESIGNATION:2
    # ATS_AIRWAY_ID:12
    # RNAV_INDICATOR:1
    # AIRWAY_TYPE:1
    # REMARK_SEQUENCE_NUMBER:3
    # REMARK_REFERENCE:5
    # REMARKS_TEXT:200
    # BLANKS:42
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # },
    # AWOS => {
    # 'AWOS1' => '
    # RECORD_TYPE_INDICATOR:5
    # WX_SENSOR_IDENT:4
    # WX_SENSOR_TYPE:10
    # COMMISSIONING_STATUS:1
    # COMMISSIONING_DECOMMISSIONING_DATE_MM_DD_YYYY:10
    # NAVAID_FLAG_WX_SENSOR_ASSOCIATED_WITH_NAVAID:1
    # STATION_LATITUDE_DD_MM_SS_SSSSH:14
    # STATION_LONGITUDE_DDD_MM_SS_SSSSH:15
    # ELEVATION:7
    # SURVEY_METHOD_CODE:1
    # STATION_FREQUENCY:7
    # SECOND_STATION_FREQUENCY:7
    # STATION_TELEPHONE_NUMBER:14
    # SECOND_STATION_TELEPHONE_NUMBER:14
    # LANDING_FACILITY_SITE_NUMBER_WHEN_STATION_LOCATED_AT_AIRPORT:11
    # STATION_CITY:40
    # STATION_STATE_POST_OFFICE_CODE:2
    # INFORMATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # BLANKS_FILLER:82
    # ',
    # 'AWOS2' => '
    # RECORD_TYPE_INDICATOR:5
    # WX_SENSOR_IDENT:4
    # WX_SENSOR_TYPE:10
    # ASOS_AWOS_REMARKS_FREE_FORM_TEXT:236
    # ',
    # },
    # AWY => {
    # 'AWY1' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # CHART_PUBLICATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # TRACK_ANGLE_OUTBOUND_RNAV_FORMAT_NNN_NNN:7
    # DISTANCE_TO_CHANGEOVER_POINT_RNAV_FORMAT_NNNNN:5
    # TRACK_ANGLE_INBOUND_RNAV_FORMAT_NNN_NNN:7
    # DISTANCE_TO_NEXT_POINT_IN_NAUTICAL_MILES_FORMAT_NNN_NN:6
    # BEARING_RESERVED_PRESENTLY_000_00_ENTERED_FORMAT_NNN_NN_OR_BLAN:6
    # SEGMENT_MAGNETIC_COURSE_FORMAT_NNN_NN_OR_BLANKS:6
    # SEGMENT_MAGNETIC_COURSE_OPPOSITE_DIRECTION_FORMAT_NNN_NN_OR_BLA:6
    # DISTANCE_TO_NEXT_POINT_IN_SEGMENT_IN_NAUTICAL_MILES_FORMAT_NNN:6
    # POINT_TO_POINT_MINIMUM_ENROUTE_ALTITUDE_MEA_FORMAT_NNNNN:5
    # POINT_TO_POINT_MINIMUM_ENROUTE_DIRECTION_MEA_FORMAT_AAAAAAA:6
    # POINT_TO_POINT_MINIMUM_ENROUTE_ALTITUDE_MEA_OPPOSITE_DIRECTION:5
    # POINT_TO_POINT_MINIMUM_ENROUTE_DIRECTION_MEA_OPPOSITE_DIRECTION:6
    # POINT_TO_POINT_MAXIMUM_AUTHORIZED_ALTITUDE:5
    # POINT_TO_POINT_MINIMUM_OBSTRUCTION_CLEARANCE_ALTITUDE_MOCA:5
    # AIRWAY_GAP_FLAG_INDICATOR:1
    # DISTANCE_FROM_THIS_POINT_TO_THE_CHANGEOVER_POINT_FOR_THE_NEXT_N:3
    # MINIMUM_CROSSING_ALTITUDE_FORMAT_NNNNN:5
    # DIRECTION_OF_CROSSING_FORMAT_AAAAAAA:7
    # MINIMUM_CROSSING_ALTITUDE_OPPOSITE_DIRECTION_FORMAT_NNNNN:5
    # DIRECTION_OF_CROSSING_OPPOSITE_DIRECTION_FORMAT_AAAAAAA:7
    # GAP_IN_SIGNAL_COVERAGE_INDICATOR:1
    # U_S_AIRSPACE_ONLY_INDICATOR:1
    # NAVAID_MAGNETIC_VARIATION:5
    # NAVAID_FIX_ARTCC_EX_ZTL:3
    # RESERVED_TO_POINT_PART95:33
    # RESERVED_NEXT_MEA_POINT_PART95:40
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:5
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_DIRECTION_GLOBAL_NAVIGATION:6
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_ALTITUDE_GLOBAL_NAVIGATION:5
    # POINT_TO_POINT_GNSS_MINIMUM_ENROUTE_DIRECTION_GLOBAL_NAVIGATION:6
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'AWY2' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # NAVAID_FACILITY_FIX_NAME:30
    # NAVAID_FACILITY_FIX_TYPE:19
    # FIX_TYPE_PUBLICATION_CATEGORY:15
    # NAVAID_FACILITY_FIX_STATE_P_O_CODE:2
    # ICAO_REGION_CODE_FOR_FIX:2
    # NAVAID_FACILITY_FIX_LATITUDE:14
    # NAVAID_FACILITY_FIX_LONGITUDE:14
    # FIX_MINIMUM_RECEPTION_ALTITUDE_MRA:5
    # NAVAID_IDENTIFIER_EX_STS_HVR:4
    # RESERVED_FROM_POINT_PART95:40
    # BLANKS:79
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'AWY3' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # NAVAID_FACILITY_NAME:30
    # NAVAID_FACILITY_TYPE:19
    # NAVAID_FACILITY_STATE_P_O_CODE:2
    # NAVAID_FACILITY_LATITUDE:14
    # NAVAID_FACILITY_LONGITUDE:14
    # BLANKS:145
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'AWY4' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # REMARKS_TEXT:202
    # BLANKS:22
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'AWY5' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # AIRWAY_POINT_SEQUENCE_NUMBER:5
    # REMARKS_TEXT:202
    # BLANKS:22
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # 'RMK' => 'RECORD_TYPE_INDICATOR:4
    # AIRWAY_DESIGNATION:5
    # AIRWAY_TYPE:1
    # REMARK_SEQUENCE_NUMBER:3
    # REMARK_REFERENCE:6
    # REMARKS_TEXT:220
    # RECORD_SORT_SEQUENCE_NUMBER:7
    # ',
    # },

    # # CDR    => {},
    # COM => {
    # 'COM' => '
    # COMMUNICATIONS_OUTLET_IDENT:4
    # COMMUNICATIONS_OUTLET_TYPE:7
    # ASSOCIATED_NAVAID_IDENT:4
    # ASSOCIATED_NAVAID_TYPE:2
    # ASSOCIATED_NAVAID_CITY:26
    # ASSOCIATED_NAVAID_STATE:20
    # ASSOCIATED_NAVAID_NAME:26
    # ASSOCIATED_NAVAID_LATITUDE:14
    # ASSOCIATED_NAVAID_LONGITUDE:14
    # COMMUNICATIONS_OUTLET_CITY:26
    # COMMUNICATIONS_OUTLET_STATE:20
    # COMMUNICATIONS_OUTLET_REGION_NAME:20
    # COMMUNICATIONS_OUTLET_REGION_CODE:3
    # COMMUNICATIONS_OUTLET_LATITUDE:14
    # COMMUNICATIONS_OUTLET_LONGITUDE:14
    # COMMUNICATIONS_OUTLET_CALL:26
    # COMMUNICATIONS_OUTLET_FREQUENCIES_IN_16_FIELDS_OF_9_CHARACTERS:144
    # FSS_IDENT:4
    # FSS_IDENT_FSS_NAME:30
    # ALTERNATE_FSS_IDENT:4
    # ALTERNATE_FSS_IDENT_ALTERNATE_FSS_NAME:30
    # OPERATIONAL_HOURS_IN_3_FIELDS_OF_20_CHARACTERS_EACH:60
    # OWNER_CODE:1
    # OWNER_NAME:69
    # OPERATOR_CODE:1
    # OPERATOR_NAME:69
    # CHARTS_IN_4_FIELDS_OF_2_CHARACTERS_EACH:8
    # STANDARD_TIME_ZONE:2
    # STATUS:20
    # STATUS_DATE:11
    # '
    # },
    # FIX => {
    # 'FIX1' => '
    # RECORD_TYPE_INDICATOR:4
    # RECORD_IDENTIFIER_FIX_ID:30
    # RECORD_IDENTIFIER_FIX_STATE_NAME:30
    # ICAO_REGION_CODE:2
    # GEOGRAPHICAL_LATITUDE_OF_THE_FIX:14
    # GEOGRAPHICAL_LONGITUDE_OF_THE_FIX:14
    # CATEGORIZES_THE_FIX_AS_A_MILITARY_MIL_OR_CIVIL_FIX_FIX:3
    # IDENT_FACILITY_TYPE_DIRECTION_OR_COURSE_OF_MLS_CO:22
    # AIRPORT_ID_APPROACH_END_RWY_DISTANCE_OF_RADAR_COMPONENT_USED_IN:22
    # PREVIOUS_NAME_OF_THE_FIX_BEFORE_IT_WAS_RENAMED:33
    # CHARTING_INFORMATION:38
    # FIX_TO_BE_PUBLISHED:1
    # FIX_USE:15
    # NATIONAL_AIRSPACE_SYSTEM_NAS_IDENTIFIER_FOR_THE_FIX_USUALLY_5_C:5
    # DENOTES_HIGH_ARTCC_AREA_OF_JURISDICTION:4
    # DENOTES_LOW_ARTCC_AREA_OF_JURISDICTION:4
    # FIX_COUNTRY_NAME_OUTSIDE_CONUS:30
    # PITCH:1
    # CATCH:1
    # SUA_ATCAA:1
    # BLANKS:192
    # ',
    # 'FIX2' => '
    # RECORD_TYPE_INDICATOR:4
    # RECORD_IDENTIFIER_FIX_NAME:30
    # RECORD_IDENTIFIER_FIX_STATE_NAME:30
    # ICAO_REGION_CODE:2
    # LOCATION_IDENTIFIER_FACILITY_TYPE_AND_RADIAL_OR_BEARING_DME_DIS:23
    # BLANKS:377
    # ',
    # 'FIX3' => '
    # RECORD_TYPE_INDICATOR:4
    # RECORD_IDENTIFIER_FIX_NAME:30
    # RECORD_IDENTIFIER_FIX_STATE_NAME:30
    # ICAO_REGION_CODE:2
    # IDENT_FACILITY_TYPE_DIRECTION_OR_COURSE_OF_ILS_CO:23
    # BLANKS:377
    # ',
    # 'FIX4' => '
    # RECORD_TYPE_INDICATOR:4
    # RECORD_IDENTIFIER_FIX_NAME:30
    # RECORD_IDENTIFIER_FIX_STATE_NAME:30
    # ICAO_REGION_CODE:2
    # FIELD_LABEL:100
    # REMARK_TEXT:300
    # ',
    # 'FIX5' => '
    # RECORD_TYPE_INDICATOR:4
    # RECORD_IDENTIFIER_FIX_NAME:30
    # RECORD_IDENTIFIER_FIX_STATE_NAME:30
    # ICAO_REGION_CODE:2
    # CHART_ON_WHICH_FIX_IS_TO_BE_DEPICTED:22
    # BLANKS:378
    # ',
    # },
    # FSS => {
    # 'FSS' =>
    # 'RECORD_IDENTIFIER_THE_FLIGHT_SERVICE_STATION_S_LOCATION_IDENT:4
    # NAME_OF_FSS:26
    # FSS_UPDATE_DATE_LAST_DATE_ON_WHICH_THE_RECORD_WAS_UPDATED:11
    # SITE_NUMBER_OF_ASSOCIATED_AIRPORT:11
    # AIRPORT_NAME_FSS_ON_ARPT:50
    # AIRPORT_ASSOCIATED_CITY_FSS_ON_ARPT:26
    # AIRPORT_ASSOCIATED_STATE_FSS_ON_ARPT:20
    # AIRPORT_LATITUDE_FSS_ON_ARPT:14
    # AIRPORT_LONGITUDE_FSS_ON_ARPT:14
    # FACILITY_TYPES:8
    # FACILITY_IDENTIFIER_FSS_NAME_AND_FSS_VOICE_CALL:26
    # FSS_OWNER_CODE:1
    # FSS_OWNER_NAME:69
    # FSS_OPERATOR_CODE:1
    # FSS_OPERATOR_NAME:69
    # PRIMARY_FSS_FREQUENCIES_USED_60_OCCURENCES_OF_40_CHARACTERS_EAC:2400
    # FSS_HOURS_OF_OPERATION:100
    # STATUS_OF_FACILITY:20
    # NAME_OF_FSS_WITH_CIRCUIT_B_TELETYPE_CAPABLE_OF_TRANSMITTING_REC:3
    # COMMUNICATIONS_OUTLET_IDENTIFICATION_40_OCCURENCES_OF_14_CHARAC:560
    # NAVAID_IDENTIFIER_AND_NAVAID_FACILITY_TYPE_OF_ASSOCIATED_NAVAID:525
    # RESERVED_WAS_F23_9_27_83:20
    # AVAILABILITY_OF_WEATHER_RADAR:1
    # ENROUTE_FLIGHT_ADVISORY_SERVICE_EFAS_AVAILABLE_ALSO_CALLED_FLIG:10
    # FLIGHT_WATCH_HOURS_OF_OPERATION:50
    # CITY_WHEN_FSS_IS_NOT_ON_AIRPORT_SEE_F6:26
    # STATE_WHEN_FSS_IS_NOT_ON_AIRPORT_SEE_F6:20
    # LATITUDE_WHEN_FSS_IS_NOT_ON_AIRPORT_SEE_F6:14
    # LONGITUDE_WHEN_FSS_IS_NOT_ON_AIRPORT_SEE_F6:14
    # REGION_WHEN_FSS_IS_NOT_ON_AIRPORT_SEE_F6:3
    # RESERVED:3
    # AIRPORT_ADVISORY_FREQUENCIES_20_OCCURENCES_OF_6_CHARACTERS_EACH:120
    # FREQUENCY_ON_WHICH_VOLMET_METEOROLOGICAL_BROADCASTS_ARE_TRANSMI:120
    # VOLMET_SCHEDULE_OF_OPERATION_20_OCCURENCES_OF_12_CHARACTERS_EAC:240
    # TYPE_OF_DIRECTION_FINDING_DF_EQUIPMENT:30
    # LATITUDE_OF_DIRECTION_FINDING_DF_EQUIPMENT:14
    # LONGITUDE_OF_DIRECTION_FINDING_DF_EQUIPMENT:14
    # LOW_ALTITUDE_ENROUTE_CHART_NUMBER_THAT_THE_FSS_IS_LOCATED_ON_20:40
    # TELEPHONE_NUMBER_USED_TO_REACH_FSS:12
    # RESERVED:50
    # FLIGHT_SERVICE_STATION_REMARKS:1050
    # CITY_FACILITY_LOCATED_IN_NOT_USED_WHEN_COLOCATED_WITH_NAVAID:780
    # STATE_FACILITY_LOCATED_IN_NOT_USED_WHEN_COLOCATED_WITH_NAVAID:600
    # GEOGRAPHICAL_LATITUDE_OF_COMMUNICATION_FACILITY_NOT_USED_WHEN_C:420
    # GEOGRAPHICAL_LONGITUDE_OF_COMMUNICATION_FACILITY_NOT_USED_WHEN:420
    # FACILITY_OWNER_CODE:40
    # FACILITY_OWNER_NAME:2760
    # FACILITY_OPERATOR_CODE:40
    # FACILITY_OPERATOR_NAME:2760
    # FSS_ASSOCIATED_WITH_THE_COMMUNICATION_FACILITY:160
    # FREQUENCIES_USED_BY_THE_COMMUNICATION_FACILITY:540
    # OPERATIONAL_HOURS_OF_THE_COMMUNICATION_FACILITY_LOCAL_TIME:800
    # STATUS_OF_COMMUNICATION_FACILITY:800
    # COMMUNICATION_FACILITY_STATUS_DATE:330
    # NAVAID_IDENTIFIER_FACT_TYPE_WHEN_COLOCATED:140
    # LOW_ALITUDE_ENROUTE_CHART_THAT_THE_COMMUNICATION_FACILITY_IS_LO:60
    # STANDARD_TIME_ZONE_THAT_THE_COMMUNICATION_IS_LOCATED_IN:40
    # COMMUNICATION_REMARKS:1050
    # DATE_INFORMATION_EXTRACTED:11
    # ',

    # #BUG TODO: Continuation records not implemented
    # '*' => '                     ',
    # },
    # HARFIX => {
    # 'HARFIX' => 'FIX_NAVAID_ID:77
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_LATITUDE_FORMAT_DDMMSS_SSSSX:12
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_LONGITUDE_FORMAT_DDDMMSS_SSSSX:13
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # TYPE:1
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # CLASS_OF_NAVAID:11
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # PITCH_POINT:1
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # CATCH_POINT:1
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # SUA_ATCAA_WAYPOINT:1
    # ',
    # '               ' => '                     ',
    # },
    # HPF => {
    # 'HP1' => 'RECORD_TYPE_INDICATOR:4
    # HOLDING_PATTERN_NAME:80
    # PATTERN_NUMBER_TO_UNIQUELY_IDENTIFY_HOLDING_PATTERN:3
    # HOLDING_PATTERN_EFFECTIVE_DATE:11
    # DIRECTION_OF_HOLDING_ON_THE_NAVAID_OR_FIX:3
    # MAGNETIC_BEARING_OR_RADIAL_DEGREES_OF_HOLDING:3
    # AZIMUTH_DEGREES_SHOWN_ABOVE_IS_A_RADIAL_COURSE_BEARING_OR_RNAV:5
    # IDENTIFIER_OF_ILS_FACILITY_USED_TO_PROVIDE_COURSE_FOR_HOLDING:7
    # IDENTIFIER_OF_NAVAID_FACILITY_USED_TO_PROVIDE_RADIAL_OR_BEARING:7
    # ADDITIONAL_FACILITY_USED_IN_HOLDING_PATTERN_MAKE_UP:12
    # INBOUND_COURSE:3
    # TURNING_DIRECTION:3
    # HOLDING_ALTITUDES_FOR_ALL_AIRCRAFT:7
    # HOLDING_ALT_170_175_KT:7
    # HOLDING_ALT_200_230_KT:7
    # HOLDING_ALT_265_KT:7
    # HOLDING_ALT_280_KT:7
    # HOLDING_ALT_310_KT:7
    # FIX_WITH_WHICH_HOLDING_IS_ASSOCIATED:36
    # ARTCC_ASSOCIATED_WITH_FIX:3
    # LATITUDE_OF_THE_ASSOCIATED_FIX_DD_MM_SS_SSSN:14
    # LONGITUDE_OF_THE_ASSOCIATED_FIX_DDD_MM_SS_SSSW:14
    # HIGH_ROUTE_ARTCC_ASSOCIATED_WITH_NAVAID:3
    # LOW_ROUTE_ARTCC_ASSOCIATED_WITH_NAVAID:3
    # LATITUDE_OF_THE_ASSOCIATED_NAVAID_DD_MM_SS_SSSN:14
    # LONGITUDE_OF_THE_ASSOCIATED_NAVAID_DDD_MM_SS_SSSW:14
    # LEG_LENGTH_OUTBOUND_TWO_SUBFIELDS_SEPARATED_BY_A_SLASH_TIME_MIN:8
    # BLANKS:195
    # ',
    # 'HP2' => 'RECORD_TYPE_INDICATOR:4
    # HOLDING_PATTERN_NAME:80
    # PATTERN_NUMBER_TO_UNIQUELY_IDENTIFY_HOLDING_PATTERN:3
    # CHARTING_DESCRIPTION:21
    # BLANKS:379
    # ',
    # 'HP3' => 'RECORD_TYPE_INDICATOR:4
    # HOLDING_PATTERN_NAME:80
    # PATTERN_NUMBER_TO_UNIQUELY_IDENTIFY_HOLDING_PATTERN:3
    # HOLDING_ALTITUDES_SPEEDS_OTHER_THAN_ONES_SHOWN_IN_HP1_RECORD:15
    # BLANKS:385
    # ',
    # 'HP4' => 'RECORD_TYPE_INDICATOR:4
    # HOLDING_PATTERN_NAME:80
    # PATTERN_NUMBER_TO_UNIQUELY_IDENTIFY_HOLDING_PATTERN:3
    # FIELD_LABEL:100
    # DESCRIPTIVE_REMARKS:300
    # ',
    # },
    # ILS => {
    # 'ILS1' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # IDENTIFICATION_CODE_OF_ILS:6
    # INFORMATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # AIRPORT_NAME_EX_CHICAGO_O_HARE_INTL:50
    # ASSOCIATED_CITY_EX_CHICAGO:40
    # TWO_LETTER_POST_OFFICE_CODE_FOR_THE_STATE:2
    # STATE_NAME:20
    # FAA_REGION_CODE:3
    # AIRPORT_IDENTIFIER:4
    # ILS_RUNWAY_LENGTH_IN_WHOLE_FEET:5
    # ILS_RUNWAY_WIDTH_IN_WHOLE_FEET:4
    # CATEGORY_OF_THE_ILS_I_II_IIIA:9
    # NAME_OF_OWNER_OF_THE_FACILITY:50
    # NAME_OF_THE_ILS_FACILITY_OPERATOR:50
    # ILS_APPROACH_BEARING_IN_DEGREES_MAGNETIC:6
    # THE_MAGNETIC_VARIATION_AT_THE_ILS_FACILITY:3
    # BLANK:88
    # ',
    # 'ILS2' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # OPERATIONAL_STATUS_OF_LOCALIZER:22
    # EFFECTIVE_DATE_OF_LOCALIZER_OPERATIONAL_STATUS:10
    # LATITUDE_OF_LOCALIZER_ANTENNA_FORMATTED:14
    # LATITUDE_OF_LOCALIZER_ANTENNA_ALL_SECONDS:11
    # LONGITUDE_OF_LOCALIZER_ANTENNA_FORMATTED:14
    # LONGITUDE_OF_LOCALIZER_ANTENNA_ALL_SECONDS:11
    # CODE_INDICATING_SOURCE_OF_LATITUDE_LONGITUDE_INFORMATION:2
    # DISTANCE_OF_LOCALIZER_ANTENNA_FROM_APPROACH_END_OF_RUNWAY_FEET:7
    # DISTANCE_OF_LOCALIZER_ANTENNA_FROM_RUNWAY_CENTERLINE_FEET:4
    # DIRECTION_OF_LOCALIZER_ANTENNA_FROM_RUNWAY_CENTERLINE:1
    # CODE_INDICATING_SOURCE_OF_DISTANCE:2
    # SITE_ELEVATION_OF_LOCALIZER_ANTENNA_IN_TENTH_OF_A_FOOT_MSL:7
    # LOCALIZER_FREQUENCY_MHZ:7
    # LOCALIZER_BAcK_COURSE_STATUS:15
    # LOCALIZER_COURSE_WIDTH_DEGREES_AND_HUNDREDTHS:5
    # LOCALIZER_COURSE_WIDTH_AT_THRESHOLD:7
    # LOCALIZER_DISTANCE_FROM_STOP_END_OF_RWY_FEET:7
    # LOCALIZER_DIRECTION_FROM_STOP_END_OF_RWY:1
    # LOCALIZER_SERVICES_CODE:2
    # BLANK:201
    # ',
    # 'ILS3' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # OPERATIONAL_STATUS_OF_GLIDE_SLOPE:22
    # EFFECTIVE_DATE_OF_GLIDE_SLOPE_OPERATIONAL_STATUS:10
    # LATITUDE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_FORMATTED:14
    # LATITUDE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_ALL_SECONDS:11
    # LONGITUDE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_FORMATTED:14
    # LONGITUDE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_ALL_SECONDS:11
    # CODE_INDICATING_SOURCE_OF_LATITUDE_LONGITUDE_INFORMATION:2
    # DISTANCE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_FROM_APPROACH_END_O:7
    # DISTANCE_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_FROM_RUNWAY_CENTERL:4
    # DIRECTION_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_FROM_RUNWAY_CENTER:1
    # CODE_INDICATING_SOURCE_OF_DISTANCE_INFORMATION:2
    # SITE_ELEVATION_OF_GLIDE_SLOPE_TRANSMITTER_ANTENNA_IN_TENTH_OF_A:7
    # GLIDE_SLOPE_CLASS_TYPE:15
    # GLIDE_SLOPE_ANGLE_IN_DEGREES_AND_HUNDREDTHS_OF_DEGREE:5
    # GLIDE_SLOPE_TRANSMISSION_FREQUENCY:7
    # ELEVATION_OF_RUNWAY_AT_POINT_ADJACENT_TO_THE_GLIDE_SLOPE_ANTENN:8
    # BLANK:210
    # ',
    # 'ILS4' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # OPERATIONAL_STATUS_OF_DME:22
    # EFFECTIVE_DATE_OF_DME_OPERATIONAL_STATUS:10
    # LATITUDE_OF_DME_TRANSPONDER_ANTENNA_FORMATTED:14
    # LATITUDE_OF_DME_TRANSPONDER_ANTENNA_ALL_SECONDS:11
    # LONGITUDE_OF_DME_TRANSPONDER_ANTENNA_FORMATTED:14
    # LONGITUDE_OF_DME_TRANSPONDER_ANTENNA_ALL_SECONDS:11
    # CODE_INDICATING_SOURCE_OF_LATITUDE_LONGITUDE_INFORMATION:2
    # DISTANCE_OF_DME_TRANSMITTER_ANTENNA_FROM_APPROACH_END_OF_RUNWAY:7
    # DISTANCE_OF_DME_TRANSPONDER_ANTENNA_FROM_RUNWAY_CENTERLINE_FEET:4
    # DIRECTION_OF_DME_TRANSPONDER_ANTENNA_FROM_RUNWAY_CENTERLINE:1
    # CODE_INDICATING_SOURCE_OF_DISTANCE_INFORMATION:2
    # SITE_ELEVATION_OF_DME_TRANSPONDER_ANTENNA_IN_TENTH_OF_A_FOOT_MS:7
    # CHANNEL_ON_WHICH_DISTANCE_DATA_IS_TRANSMITTED:4
    # DISTANCE_OF_DME_ANTENNA_FROM_STOP_END_OF_RUNWAY:7
    # BLANK:234
    # ',
    # 'ILS5' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # MARKER_TYPE:2
    # OPERATIONAL_STATUS_OF_MARKER_BEACON:22
    # EFFECTIVE_DATE_OF_MARKER_BEACON_OPERATIONAL_STATUS:10
    # LATITUDE_OF_MARKER_BEACON_FORMATTED:14
    # LATITUDE_OF_MARKER_BEACON_ALL_SECONDS:11
    # LONGITUDE_OF_MARKER_BEACON_FORMATTED:14
    # LONGITUDE_OF_MARKER_BEACON_ALL_SECONDS:11
    # CODE_INDICATING_SOURCE_OF_LATITUDE_LONGITUDE_INFORMATION:2
    # DISTANCE_OF_MARKER_BEACON_FROM_APPROACH_END_OF_RUNWAY_FEET:7
    # DISTANCE_OF_MARKER_BEACON_FROM_RUNWAY_CENTERLINE_FEET:4
    # DIRECTION_OF_MARKER_BEACON_FROM_RUNWAY_CENTERLINE:1
    # CODE_INDICATING_SOURCE_OF_DISTANCE_INFORMATION:2
    # SITE_ELEVATION_OF_MARKER_BEACON_IN_TENTH_OF_A_FOOT_MSL:7
    # FACILITY_TYPE_OF_MARKER_LOCATOR:15
    # LOCATION_IDENTIFIER_OF_BEACON_AT_MARKER:2
    # NAME_OF_THE_MARKER_LOCATOR_BEACON:30
    # FREQUENCY_OF_LOCATOR_BEACON_AT_MIDDLE_MARKER_IN_KHZ:3
    # LOCATION_IDENTIFIER_NAVAID_TYPE_OF_NAVIGATION_AID_COLOCATED_WIT:25
    # LOW_POWERED_NDB_STATUS_OF_MARKER_BEACON:22
    # SERVICE_PROVIDED_BY_MARKER:30
    # BLANK:116
    # ',
    # 'ILS6' => 'RECORD_TYPE_INDICATOR:4
    # AIRPORT_SITE_NUMBER_IDENTIFIER:11
    # ILS_RUNWAY_END_IDENTIFIER:3
    # ILS_SYSTEM_TYPE:10
    # ILS_REMARKS_FREE_FORM_TEXT:350
    # ',
    # },
    # LID => {
    # '1' => 'IDENTIFIER_GROUP_SORT_CODE:1
    # IDENTIFIER_GROUP_CODE:3
    # LOCATION_IDENTIFIER:5
    # FAA_REGION_ASSOCIATED_WITH_THE_LOCATION_IDENTIFIER:3
    # STATE_ASSOCIATED_WITH_THE_LOCATION_IDENTIFIER_ALPHABETIC_POST_O:2
    # CITY_ASSOCIATED_WITH_THE_LOCATION_IDENTIFIER:40
    # CONTROLLING_ARTCC_FOR_THIS_LOCATION:4
    # CONTROLLING_ARTCC_FOR_THIS_LOCATION_COMPUTER_ID:3
    # LANDING_FACILITY_NAME:50
    # LANDING_FACILITY_TYPE:13
    # TIE_IN_FLIGHT_SERVICE_STATION_FSS_IDENTIFIER:4
    # NAVAID_FACILITY_NAME_1:30
    # NAVAID_FACILITY_TYPE_1:20
    # NAVAID_FACILITY_NAME_2:30
    # NAVAID_FACILITY_TYPE_2:20
    # NAVAID_FACILITY_NAME_3:30
    # NAVAID_FACILITY_TYPE_3:20
    # NAVAID_FACILITY_NAME_4:30
    # NAVAID_FACILITY_TYPE_4:20
    # TIE_IN_FLIGHT_SERVICE_STATION_FSS_IDENTIFIER:4
    # ILS_RUNWAY_END_EX_08_18R_36L:3
    # ILS_FACILITY_TYPE:20
    # LOCATION_IDENTIFIER_OF_ILS_AIRPORT:5
    # ILS_AIRPORT_NAME:50
    # TIE_IN_FLIGHT_SERVICE_STATION_FSS_IDENTIFIER:4
    # FSS_NAME:30
    # ARTCC_NAME:30
    # ARTCC_FACILITY_TYPE:17
    # FLIGHT_WATCH_STATION_FLTWO_INDICATOR:1
    # OTHER_FACILITY_FACILITY_NAME_DESCRIPTION:75
    # OTHER_FACILITY_FACILITY_TYPE:15
    # EFFECTIVE_DATE_OF_THIS_INFORMATION_MM_DD_YYYY:10
    # BLANKS:447
    # ',
    # '2' => 'IDENTIFIER_GROUP_SORT_CODE:1
    # IDENTIFIER_GROUP_CODE:3
    # LOCATION_IDENTIFIER:5
    # COUNTRY_ASSOCIATED_WITH_THE_LOCATION_IDENTIFIER:30
    # SECOND_LEVEL_QUALIFIER_OF_LOCATION_DESCRIPTION:20
    # CITY_LOCATION_ASSOCIATED_WITH_THE_IDENTIFIER:50
    # LANDING_FACILITY_NAME:50
    # LANDING_FACILITY_TYPE:20
    # NAVAID_FACILITY_NAME_1:50
    # NAVAID_FACILITY_TYPE_1:20
    # NAVAID_FACILITY_NAME_2:50
    # NAVAID_FACILITY_TYPE_2:20
    # OTHER_FACILITY_NAME_1:50
    # OTHER_FACILITY_TYPE_1:20
    # OTHER_FACILITY_NAME_2:50
    # OTHER_FACILITY_TYPE_2:20
    # EFFECTIVE_DATE_OF_THIS_INFORMATION_MM_DD_YYYY:10
    # BLANKS:570
    # ',
    # '3' => 'IDENTIFIER_GROUP_SORT_CODE:1
    # IDENTIFIER_GROUP_CODE:3
    # LOCATION_IDENTIFIER:5
    # CANADIAN_PROVINCE_ASSOCIATED_WITH_THE_LOCATION_IDENTIFIER:10
    # CITY_LOCATION_ASSOCIATED_WITH_THE_IDENTIFIER:50
    # LANDING_FACILITY_NAME_1:50
    # LANDING_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_1:50
    # LANDING_FACILITY_TYPE_1:20
    # LANDING_FACILITY_NAME_2:50
    # LANDING_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_2:50
    # LANDING_FACILITY_TYPE_2:20
    # LANDING_FACILITY_NAME_3:50
    # LANDING_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_3:50
    # LANDING_FACILITY_TYPE_3:20
    # NAVAID_FACILITY_NAME_1:30
    # NAVAID_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_1:50
    # NAVAID_FACILITY_TYPE_1:20
    # NAVAID_FACILITY_NAME_2:30
    # NAVAID_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_2:50
    # NAVAID_FACILITY_TYPE_2:20
    # ILS_FACILITY_NAME_1:30
    # ILS_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_1:50
    # ILS_FACILITY_TYPE_1:20
    # ILS_FACILITY_NAME_2:30
    # ILS_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_2:50
    # ILS_FACILITY_TYPE_2:20
    # OTHER_FACILITY_NAME_1:30
    # OTHER_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_1:50
    # OTHER_FACILITY_TYPE_1:20
    # OTHER_FACILITY_NAME_2:30
    # OTHER_FACILITY_ADDITIONAL_DESCRIPTIVE_TEXT_2:50
    # OTHER_FACILITY_TYPE_2:20
    # EFFECTIVE_DATE_OF_THIS_INFORMATION_MM_DD_YYYY:10
    # ',
    # },
    # MTR => {
    # 'MTR1' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # PUBLICATION_EFFECTIVE_DATE_YYYYMMDD:8
    # FAA_REGION_CODE:3
    # ARTCC_IDENT_20_OCCURENCES_OF_4_CHARACTER_IDENT:80
    # ALL_FLIGHT_SERVICE_STATION_FSS_IDENTS_WITHIN_150_NAUTICAL_MILES:160
    # TIMES_OF_USE_TEXT_INFORMATION:50
    # BLANKS:201
    # SORT_SEQUENCE_NUMBER_FOR_RECORD:5
    # ',
    # 'MTR2' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # STANDARD_OPERATING_PROCEDURE_TEXT:100
    # BLANKS:402
    # SORT_SEQUENCE_NUMBER_FOR_RECORD:5
    # ',
    # 'MTR3' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # ROUTE_WIDTH_DESCRIPTION_TEXT:100
    # BLANKS:402
    # RECORD_SORT_SEQUENCE_NUMBER:5
    # ',
    # 'MTR4' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # TERRAIN_FOLLOWING_OPERATIONS_TEXT:100
    # BLANKS:402
    # RECORD_SORT_SEQUENCE_NUMBER:5
    # ',
    # 'MTR5' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # ROUTE_POINT_ID_A_B_C_ETC:5
    # SEGMENT_DESCRIPTION_TEXT_LEADING_UP_TO_THE_POINT_MAXIMUM_OF_4_O:228
    # SEGMENT_DESCRIPTION_TEXT_LEAVING_THE_POINT_MAXIMUM_OF_4_OCCUREN:228
    # IDENT_OF_RELATED_NAVAID:4
    # BEARING_OF_NAVAID_FROM_POINT:5
    # DISTANCE_OF_NAVAID_FROM_POINT:4
    # LATITUDE_LOCATION_OF_POINT:14
    # LONGITUDE_LOCATION_OF_POINT:14
    # RECORD_SORT_SEQUENCE_NUMBER_SEGMENT_SEQUENCE_NUMBER_FOR_THIS_PO:5
    # ',
    # 'MTR6' => 'RECORD_TYPE_INDICATOR:4
    # ROUTE_TYPE:3
    # ROUTE_IDENTIFIER:5
    # AGENCY_TYPE_CODE:2
    # AGENCY_ORGANIZATION_NAME:61
    # AGENCY_STATION:30
    # AGENCY_ADDRESS:35
    # AGENCY_CITY:30
    # AGENCY_STATE_ALPHA_POST_OFFICE_CODE:2
    # AGENCY_ZIP_CODE:10
    # AGENCY_PHONE_NUMBER:40
    # AGENCY_AUTOVON_PHONE_NUMBER:14
    # AGENCY_HOURS:40
    # BLANKS:238
    # RECORD_SORT_SEQUENCE_NUMBER:5
    # ',
    # },
    # NATFIX => {
    # 'NATFIX' => 'CHARACTER_I_THAT_INDICATES_BEGINNING_OF_RECORD:1
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_AIRPORT_ID:5
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_AIRPORT_LATITUDE_FORMAT_DDMMSSX:7
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_AIRPORT_LONGITUDE_FORMAT_DDDMMSSX:8
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # SINGLE_QUOTE_CHARACTER_THAT_PRECEDES_ARTCC_ID:1
    # ARTCC_ID:4
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # STATE_POST_OFFICE_CODE:2
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # ICAO_REGION_CODE:2
    # BLANK_CHARACTER_SEPARATING_FIELDS:1
    # FIX_NAVAID_TYPE_OR_STRING_ARPT:7
    # ',
    # },
    # NAV => {
    # 'NAV1' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACILITY_TYPE_SEE_DESCRIPTION:20
    # OFFICIAL_NAVAID_FACILITY_IDENTIFIER:4
    # EFFECTIVE_DATE_THIS_DATE_COINCIDES_WITH:10
    # NAME_OF_NAVAID_EX_WASHINGTON:30
    # CITY_ASSOCIATED_WITH_THE_NAVAID:40
    # STATE_NAME_WHERE_ASSOCIATED_CITY_IS_LOCATED:30
    # STATE_POST_OFFICE_CODE_WHERE_ASSOCIATED:2
    # FAA_REGION_RESPONSIBLE_FOR_NAVAID_CODE:3
    # COUNTRY_NAVAID_LOCATED_IF_OTHER_THAN_U_S:30
    # COUNTRY_POST_OFFICE_CODE_NAVAID:2
    # NAVAID_OWNER_NAME_EX_U_S_NAVY:50
    # NAVAID_OPERATOR_NAME_EX_U_S_NAVY:50
    # COMMON_SYSTEM_USAGE_Y_OR_N:1
    # NAVAID_PUBLIC_USE_Y_OR_N:1
    # CLASS_OF_NAVAID:11
    # HOURS_OF_OPERATION_OF_NAVAID:11
    # IDENTIFIER_OF_ARTCC_WITH_HIGH_ALTITUDE_BOUNDARY_THAT_THE_NAVAID:4
    # NAME_OF_ARTCC_WITH_HIGH_ALTITUDE_BOUNDARY_THAT_THE_NAVAID_FALLS:30
    # IDENTIFIER_OF_ARTCC_WITH_LOW_ALTITUDE_BOUNDARY_THAT_THE_NAVAID:4
    # NAME_OF_ARTCC_WITH_LOW_ALTITUDE_BOUNDARY_THAT_THE_NAVAID_FALLS:30
    # NAVAID_LATITUDE_FORMATTED:14
    # NAVAID_LATITUDE_ALL_SECONDS:11
    # NAVAID_LONGITUDE_FORMATTED:14
    # NAVAID_LONGITUDE_ALL_SECONDS:11
    # LATITUDE_LONGITUDE_SURVERY_ACCURACY_CODE:1
    # LATITUDE_OF_TACAN_PORTION_OF_VORTAC_WHEN_TACAN_IS_NOT_SITED_WIT:14
    # LATITUDE_OF_TACAN_PORTION_OF_VORTAC_WHEN_TACAN_IS_NOT_SITED_WIT:11
    # LONGITUDE_OF_TACAN_PORTION_OF_VORTAC_WHEN_TACAN_IS_NOT_SITED_WI:14
    # LONGITUDE_OF_TACAN_PORTION_OF_VORTAC_WHEN_TACAN_IS_NOT_SITED_WI:11
    # ELEVATION_IN_TENTH_OF_A_FOOT_MSL:7
    # MAGNETIC_VARIATION_DEGREES_00_99:5
    # MAGNETIC_VARIATION_EPOCH_YEAR_00_99:4
    # SIMULTANEOUS_VOICE_FEATURE_Y_N_OR_NULL:3
    # POWER_OUTPUT_IN_WATTS:4
    # AUTOMATIC_VOICE_IDENTIFICATION_FEATURE:3
    # MONITORING_CATEGORY:1
    # RADIO_VOICE_CALL_NAME:30
    # CHANNEL_TACAN_NAVAID_TRANSMITS_ON:4
    # FREQUENCY_THE_NAVAID_TRANSMITS_ON_EXCEPT_TACAN:6
    # TRANSMITTED_FAN_MARKER_MARINE_RADIO_BEACON_IDENTIFIER:24
    # FAN_MARKER_TYPE_BONE_OR_ELLIPTICAL:10
    # TRUE_BEARING_OF_MAJOR_AXIS_OF_FAN_MARKER:3
    # PROTECTED_FREQUENCY_ALTITUDE:1
    # LOW_ALTITUDE_FACILITY_USED_IN_HIGH_STRUCTURE:3
    # NAVAID_Z_MARKER_AVAILABLE_Y_N_OR_NULL:3
    # TRANSCRIBED_WEATHER_BROADCAST_HOURS_TWEB:9
    # TRANSCRIBED_WEATHER_BROADCAST_PHONE_NUMBER:20
    # ASSOCIATED_CONTROLLING_FSS_IDENT:4
    # ASSOCIATED_CONTROLLING_FSS_NAME:30
    # HOURS_OF_OPERATION_OF_CONTROLLING_FSS:100
    # NOTAM_ACCOUNTABILITY_CODE_IDENT:4
    # QUADRANT_IDENTIFICATION_AND_RANGE_LEG_BEARING:16
    # NAVIGATION_AID_STATUS:30
    # PITCH_FLAG_Y_OR_N:1
    # CATCH_FLAG_Y_OR_N:1
    # SUA_ATCAA_FLAG_Y_OR_N:1
    # NAVAID_RESTRICTION_FLAG:1
    # HIWAS_FLAG:1
    # TRANSCRIBED_WEATHER_BROADCAST_TWEB_RESTRICTION:1
    # ',
    # 'NAV2' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACITITY_TYPE_EX_VOR_DME:20
    # NAVAID_REMARKS_FREE_FORM_TEXT:600
    # FILLER:174
    # ',
    # 'NAV3' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACITITY_TYPE_EX_VOR_DME:20
    # NAME_S_OF_FIXES_FIX_FILE:36
    # SPACE_ALLOCATED_FOR_20_MORE_FIXES:720
    # BLANKS:18
    # ',
    # 'NAV4' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACITITY_TYPE_EX_VOR_DME:20
    # NAME_S_OF_HOLDING_PATTERN_S_AND_THE_STATE_IN_WHICH_THE_HOLDING:80
    # PATTERN_NUMBER_OF_THE_HOLDING_PATTERN:3
    # SPACE_ALLOCATED_FOR_8_MORE_HOLDING_PATTERNS:664
    # BLANKS:27
    # ',
    # 'NAV5' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACITITY_TYPE_EX_VOR_DME:20
    # NAME_S_OF_FAN_MARKER_S:30
    # SPACE_ALLOCATED_FOR_23_MORE_FAN_MARKERS:690
    # BLANKS:54
    # ',
    # 'NAV6' => 'RECORD_TYPE_INDICATOR:4
    # NAVAID_FACILITY_IDENTIFIER:4
    # NAVAID_FACITITY_TYPE_EX_VOR_DME:20
    # AIR_GROUND_CODE:2
    # BEARING_OF_CHECKPOINT:3
    # ALTITUDE_ONLY_WHEN_CHECKPOINT_IS_IN_AIR:5
    # AIRPORT_ID:4
    # STATE_CODE_IN_WHICH_ASSOCIATED_CITY_IS_LOCATED:2
    # NARRATIVE_DESCRIPTION_ASSOCIATED_WITH_THE_CHECKPOINT_IN_AIR:75
    # NARRATIVE_DESCRIPTION_ASSOCIATED_WITH_THE_CHECKPOINT_ON_GROUND:75
    # BLANKS:608
    # ',
    # },
    # PFR => {
    # 'PFR1' => 'RECORD_TYPE_INDICATOR:4
    # ORIGIN_FACILITY_LOCATION_IDENTIFIER:5
    # DESTINATION_FACILITY_LOCATION_IDENTIFIER:5
    # TYPE_OF_PREFERRED_ROUTE_CODE:3
    # ROUTE_IDENTIFIER_SEQUENCE_NUMBER_1_99:2
    # TYPE_OF_PREFERRED_ROUTE_DESCRIPTION:30
    # PREFERRED_ROUTE_AREA_DESCRIPTION:75
    # PREFERRED_ROUTE_ALTITUDE_DESCRIPTION:40
    # AIRCRAFT_ALLOWED_LIMITATIONS_DESCRIPTION:50
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_1:15
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_2:15
    # EFFECTIVE_HOURS_GMT_DESCRIPTION_3:15
    # ROUTE_DIRECTION_LIMITATIONS_DESCRIPTION:20
    # ',
    # 'PFR2' => 'RECORD_TYPE_INDICATOR:4
    # ORIGIN_FACILITY_LOCATION_IDENTIFIER:5
    # DESTINATION_FACILITY_LOCATION_IDENTIFIER:5
    # TYPE_OF_PREFERRED_ROUTE_CODE:3
    # ROUTE_IDENTIFIER_SEQUENCE_NUMBER_1_99:2
    # SEGMENT_SEQUENCE_NUMBER_WITHIN_THE_ROUTE:3
    # SEGMENT_IDENTIFIER:48
    # SEGMENT_TYPE:7
    # FIX_STATE_CODE_POST_OFFICE_ALPHA_CODE:2
    # ICAO_REGION_CODE:2
    # NAVAID_FACILITY_TYPE_CODE:2
    # NAVAID_FACILITY_TYPE_DESCRIBED:20
    # RADIAL_AND_DISTANCE_FROM_NAVAID:7
    # BLANK:169
    # ',
    # },
    # PJA => {
    # 'PJA1' => 'RECORD_TYPE_INDICATOR:4
    # PJA_ID:6
    # NAVAID_IDENTIFIER:4
    # NAVAID_FACILITY_TYPE_CODE:2
    # NAVAID_FACILITY_TYPE_DESCRIBED:25
    # AZIMUTH_DEGREES_FROM_NAVAID:6
    # DISTANCE_IN_NAUTICAL_MILES_FROM_NAVAID:8
    # NAVAID_NAME:30
    # PJA_STATE_ABBREVIATION_TWO_LETTER_POST_OFFICE:2
    # PJA_STATE_NAME:30
    # PJA_ASSOCIATED_CITY_NAME:30
    # PJA_LATITUDE_FORMATTED:14
    # PJA_LATITUDE_SECONDS:12
    # PJA_LONGITUDE_FORMATTED:15
    # PJA_LONGITUDE_SECONDS:12
    # ASSOCIATED_AIRPORT_NAME:50
    # ASSOCIATED_AIRPORT_SITE_NUMBER:11
    # PJA_DROP_ZONE_NAME:50
    # PJA_MAXIMUM_ALTITUDE_ALLOWED:8
    # PJA_AREA_RADIUS_IN_NAUTICAL_MILES_FROM_CENTER_POINT:5
    # SECTIONAL_CHARTING_REQUIRED:3
    # AREA_TO_BE_PUBLISHED_IN_AIRPORT_FACILITY_DIRECTORY:3
    # ADDITIONAL_DESCRIPTIVE_TEXT_FOR_AREA:100
    # ASSOCIATED_FSS_IDENT:4
    # ASSOCIATED_FSS_NAME:30
    # PJA_USE:8
    # VOLUME:1
    # ',
    # 'PJA2' => 'RECORD_TYPE_INDICATOR:4
    # PJA_ID:6
    # TIMES_OF_USE_DESCRIPTION:75
    # BLANKS:388
    # ',
    # 'PJA3' => 'RECORD_TYPE_INDICATOR:4
    # PJA_ID:6
    # PJA_USER_GROUP_NAME:75
    # DESCRIPTION:75
    # BLANKS:313
    # ',
    # 'PJA4' => 'RECORD_TYPE_INDICATOR:4
    # PJA_ID:6
    # CONTACT_FACILITY_ID:4
    # CONTACT_FACILITY_NAME_TYPE_OF_FACILITY_CONCATENATED_TO_NAME:48
    # RELATED_LOC_ID:4
    # COMMERCIAL_FREQUENCY:8
    # COMMERCIAL_CHART_FLAG:1
    # MILITARY_FREQUENCY:8
    # MILITARY_CHART_FLAG:1
    # SECTOR:30
    # ALTITUDE:20
    # BLANKS:339
    # ',
    # 'PJA5' => 'RECORD_TYPE_INDICATOR:4
    # PJA_ID:6
    # ADDITIONAL_REMARKS:300
    # BLANKS:163
    # ',
    # },
    # SSD => {
    # 'SSD' => 'INTERNAL_SEQUENCE_NUMBER:5
    # NOT_USED:5
    # FIX_FACILITY_TYPE_CODE:2
    # NOT_USED:1
    # FIX_NAVAID_AIRPORT_LATITUDE_FORMAT_XDDMMSST:8
    # FIX_NAVAID_AIRPORT_LONGITUDE_FORMAT_XDDDMMSST:9
    # FIX_NAVAID_AIRPORT_IDENTIFIER:6
    # ICAO_REGION_CODE_FIX_ONLY:2
    # STAR_SID_COMPUTER_CODE:13
    # STAR_SID_TRANSITION_NAME:110
    # AIRWAYS_NAVAIDS_USING_NUMBERED_FIX:62
    # ',
    # },
    # STARDP => {
    # 'STARDP' => 'INTERNAL_SEQUENCE_NUMBER:5
    # NOT_USED:5
    # FIX_FACILITY_TYPE_CODE:2
    # NOT_USED:1
    # FIX_NAVAID_AIRPORT_LATITUDE_FORMAT_XDDMMSST:8
    # FIX_NAVAID_AIRPORT_LONGITUDE_FORMAT_XDDDMMSST:9
    # FIX_NAVAID_AIRPORT_IDENTIFIER:6
    # ICAO_REGION_CODE_FIX_ONLY:2
    # STAR_DP_COMPUTER_CODE:13
    # STAR_DP_TRANSITION_NAME:110
    # AIRWAYS_NAVAIDS_USING_NUMBERED_FIX:62
    # ',
    # },
    # TWR => {
    # 'TWR1' => '
    # RECORD_TYPE_INDICATOR:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # INFORMATION_EFFECTIVE_DATE_MM_DD_YYYY:10
    # LANDING_FACILITY_SITE_NUMBER:11
    # FAA_REGION_CODE:3
    # ASSOCIATED_STATE_NAME:30
    # ASSOCIATED_STATE_POST_OFFICE_CODE:2
    # ASSOCIATED_CITY_NAME:40
    # OFFICIAL_AIRPORT_NAME:50
    # AIRPORT_REFERENCE_POINT_LATITUDE_FORMATTED:14
    # AIRPORT_REFERENCE_POINT_LATITUDE_SECONDS:11
    # AIRPORT_REFERENCE_POINT_LONGITUDE_FORMATTED:14
    # AIRPORT_REFERENCE_POINT_LONGITUDE_SECONDS:11
    # TIE_IN_FLIGHT_SERVICE_STATION_FSS_IDENTIFIER:4
    # TIE_IN_FLIGHT_SERVICE_STATION_FSS_NAME:30
    # FACILITY_TYPE:12
    # NUMBER_OF_HOURS_OF_DAILY_OPERATION:2
    # NUMBER_OF_HOURS_OF_DAILY_OPERATION:3
    # MASTER_AIRPORT_LOCATION_IDENTIFIER_EX_LAX:4
    # NAME_OF_MASTER_AIRPORT_FURNISHING_SERVICES_IF_THIS_FACILITY_IS:50
    # DIRECTION_FINDING_EQUIPMENT_TYPE:15
    # NAME_OF_ASSOCIATED_LANDING_FACILITY_WHEN_THE_TERMINAL_FACILITY:50
    # NAME_OF_THE_ASSOCIATED_CITY_WHEN_THE_FACILITY_NOT_LOCATED_ON_TH:40
    # NAME_OF_THE_STATE_OR_PROVINCE_WHEN_THE_FACILITY_NOT_LOCATED_ON:20
    # NAME_OF_STATE_COUNTRY_WHEN_FACILITY_NOT_LOCATED_ON_AIRPORT_OR_W:25
    # COUNTRY_STATE_POST_OFFICE_CODE_WHEN_FACILITY_NOT_LOCATED_ON_AIR:2
    # FAA_REGION_CODE_WHEN_THE_FACILITY_NOT_LOCATED_ON_THE_AIRPORT_OR:3
    # AIRPORT_SURVEILLANCE_RADAR_LATITUDE_FORMATTED:14
    # AIRPORT_SURVEILLANCE_RADAR_LATITUDE_SECONDS:11
    # AIRPORT_SURVEILLANCE_RADAR_LONGITUDE_FORMATTED:14
    # AIRPORT_SURVEILLANCE_RADAR_LONGITUDE_SECONDS:11
    # LATITUDE_OF_DIRECTION_FINDING_ANTENNA_FORMATTED:14
    # LATITUDE_OF_DIRECTION_FINDING_ANTENNA_SECONDS:11
    # LONGITUDE_OF_DIRECTION_FINDING_ANTENNA_FORMATTED:14
    # LONGITUDE_OF_DIRECTION_FINDING_ANTENNA_SECONDS:11
    # NAME_OF_THE_AGENCY_THAT_OPERATES_THE_TOWER:40
    # NAME_OF_THE_AGENCY_THAT_OPERATES_MILITARY_OPERATIONS:40
    # NAME_OF_THE_AGENCY_THAT_OPERATES_THE_PRIMARY_APPROACH_CONTROL_F:40
    # NAME_OF_THE_AGENCY_OPERATING_THE_SECONDARY_APPROACH_CONTROL_FAC:40
    # NAME_OF_THE_AGENCY_OPERATING_THE_PRIMARY_DEPARTURE_CONTROL_FACI:40
    # NAME_OF_THE_AGENCY_OPERATING_THE_SECONDARY_DEPARTURE_CONTROL_FA:40
    # RADIO_CALL_USED_BY_PILOT_TO_CONTACT_TOWER:26
    # RADIO_CALL_NAME_FOR_MILITARY_OPERATIONS_AT_THIS_AIRPORT:26
    # RADIO_CALL_OF_FACILITY_THAT_FURNISHES_PRIMARY_APPROACH_CONTROL:26
    # RADIO_CALL_OF_FACILITY_THAT_TAKES_OVER_APPROACH_CONTROL_WHEN_PR:26
    # RADIO_CALL_OF_FACILITY_THAT_FURNISHES_PRIMARY_DEPARTURE_CONTROL:26
    # RADIO_CALL_OF_FACILITY_THAT_TAKES_OVER_DEPARTURE_CONTROL_WHEN_P:26
    # BLANK:648
    # ',
    # 'TWR2' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # HOURS_OF_OPERATION_OF_THE_MILITARY_PILOT_TO_METRO_SERVICE_PMSV:200
    # HOURS_OF_OPERATION_OF_THE_MILITARY_AIRCRAFT_COMMAND_POST_MACP_L:200
    # HOURS_OF_MILITARY_OPERATIONS_CONDUCTED_EACH_DAY:200
    # HOURS_OF_OPERATION_OF_PRIMARY_APPROACH_CONTROL_FACILITY_IN_LOCA:200
    # HOURS_OF_OPERATION_OF_SECONDARY_APPROACH_CONTROL_FACILITY_IN_LO:200
    # HOURS_OF_OPERATION_OF_PRIMARY_DEPARTURE_CONTROL_FACILITY_IN_LOC:200
    # HOURS_OF_OPERATION_OF_SECONDARY_DEPARTURE_CONTROL_FACILITY_IN_L:200
    # HOURS_OF_TOWER_OPERATION_IN_LOCAL_TIME:200
    # ',
    # 'TWR3' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_1:44
    # FREQUENCY_USE_1:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_2:44
    # FREQUENCY_USE_2:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_3:44
    # FREQUENCY_USE_3:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_4:44
    # FREQUENCY_USE_4:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_5:44
    # FREQUENCY_USE_5:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_6:44
    # FREQUENCY_USE_6:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_7:44
    # FREQUENCY_USE_7:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_8:44
    # FREQUENCY_USE_8:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_9:44
    # FREQUENCY_USE_9:50
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_1:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_2:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_3:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_4:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_5:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_6:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_7:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_8:60
    # FREQUENCY_S_FOR_MASTER_AIRPORT_USE_ONLY_AND_SECTORIZATION_NOT_9:60
    # BLANK:214
    # ',
    # 'TWR4' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # MASTER_AIRPORT_SERVICES:100
    # BLANK:1500
    # ',
    # 'TWR5' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # RADAR_OR_NON_RADAR_PRIMARY_APPROACH_CALL:9
    # RADAR_OR_NON_RADAR_SECONDARY_APPROACH_CALL:9
    # RADAR_OR_NON_RADAR_PRIMARY_DEPARTURE_CALL:9
    # RADAR_OR_NON_RADAR_SECONDARY_DEPARTURE_CALL:9
    # TYPE_OF_RADAR_AT_THE_TOWER_1:10
    # RADAR_HOURS_OF_OPERATION_1:200
    # TYPE_OF_RADAR_AT_THE_TOWER_2:10
    # RADAR_HOURS_OF_OPERATION_2:200
    # TYPE_OF_RADAR_AT_THE_TOWER_3:10
    # RADAR_HOURS_OF_OPERATION_3:200
    # TYPE_OF_RADAR_AT_THE_TOWER_4:10
    # RADAR_HOURS_OF_OPERATION_4:200
    # BLANK:724
    # ',
    # 'TWR6' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # TOWER_ELEMENT_NUMBER:5
    # TOWER_REMARK_TEXT:800
    # BLANK:795
    # ',
    # 'TWR7' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # SATELLITE_FREQUENCY:44
    # SATELLITE_FREQUENCY_USE:50
    # SATELLITE_AIRPORT_SITE_NUMBER:11
    # SATELLITE_AIRPORT_LOCATION_IDENTIFIER_MAY_BE_USED_AS_A_LINK_TO:4
    # SATELLITE_FAA_REGION_CODE:3
    # SATELLITE_ASSOCIATED_STATE_NAME:30
    # SATELLITE_ASSOCIATED_STATE_POST_OFFICE_CODE:2
    # SATELLITE_ASSOCIATED_CITY:40
    # SATELLITE_ARPT_NAME:50
    # AIRPORT_LATITUDE_FORMATTED:14
    # AIRPORT_LATITUDE_SECONDS:11
    # AIRPORT_LONGITUDE_FORMATTED:14
    # AIRPORT_LONGITUDE_SECONDS:11
    # FLIGHT_SERVICE_STATION_IDENTIFIER:4
    # FLIGHT_SERVICE_STATION_NAME:30
    # MASTER_AIRPORT_INFORMATION:11
    # MASTER_AIRPORT_FAA_REGION_CODE:3
    # MASTER_AIRPORT_ASSOCIATED_STATE_NAME:30
    # MASTER_AIRPORT_ASSOCIATED_STATE_POST_OFFICE:2
    # MASTER_AIRPORT_ASSOCIATED_CITY:40
    # MASTER_AIRPORT_NAME:50
    # SATELLITE_FREQUENCY_NOT_TRUNCATED:60
    # BLANK:1086
    # ',
    # 'TWR8' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # CLASS_B_AIRSPACE:1
    # CLASS_C_AIRSPACE:1
    # CLASS_D_AIRSPACE:1
    # CLASS_E_AIRSPACE:1
    # AIRSPACE_HOURS:300
    # BLANK:1296
    # ',
    # 'TWR9' => '
    # RECORD_IDENTIFIER:4
    # TERMINAL_COMMUNICATIONS_FACILITY_IDENTIFIER:4
    # ATIS_SERIAL_NUMBER:4
    # ATIS_HOURS_OF_OPERATION_IN_LOCAL_TIME:200
    # OPTIONAL_DESCRIPTION_OF_PURPOSE_FULFILLED_BY_ATIS:100
    # ATIS_PHONE_NUMBER:18
    # BLANK:1278
    # ',
    # },
    # WXL => {
    # 'WXL' => '
    # WEATHER_REPORTING_LOCATION_IDENTIFIER:5
    # LATITUDE_OF_THE_WEATHER_REPORTING_LOCATION:8
    # LONGITUDE_OF_THE_WEATHER_REPORTING_LOCATION_FORMAT_DDDMMSSTC:9
    # ASSOCIATED_CITY:26
    # ASSOCIATED_STATE_POST_OFFICE_CODE:2
    # ASSOCIATED_COUNTRY_NUMERIC_CODE_NON_US_ONLY:3
    # WEATHER_REPORTING_LOCATION_ELEVATION_VALUE_WHOLE_FEET_MSL:5
    # WEATHER_REPORTING_LOCATION_ELEVATION_ACCURACY:1
    # WEATHER_SERVICES_AVAILABLE_AT_LOCATION_UP_TO:60
    # BLANK:2
    # ',

    # #BUG: These aren't implemented yet
    # '*1' => '
    # CONTINUATION_RECORD_INDICATOR:1
    # COLLECTIVE_WEATHER_SERVICE_TYPE:5
    # COLLECTIVE_NUMBER:1
    # BLANK:114
    # ',
    # '*2' => '
    # CONTINUATION_RECORD_INDICATOR:1
    # AFFECTED_AREA_WEATHER_SERVICE_TYPE:5
    # AFFECTED_AREAS_STATES_AREAS:114
    # BLANK:1
    # ',
    # },

    OBSTACLE => {
        'OBSTACLE' => '
        ORS_Code:2
        Dash:1
        Obstacle_Number:6
        Blank:1
        Verification_Status:1
        Blank:1
        Country_Identifier:2
        Blank:1
        State_Identifier:2
        Blank:1
        City_Name:16
        Blank:1
        Latitude_Degrees:2
        Blank:1
        Latitude_Minutes:2
        Blank:1
        Latitude_Seconds:5
        Latitude_Hemisphere:1
        Blank:1
        Longitude_Degrees:3
        Blank:1
        Longitude_Minutes:2
        Blank:1
        Longitude_Seconds:5
        Longitude_Hemisphere:1
        Blank:1
        Obstacle_Type:12
        Blank:1
        Quantity:1
        Blank:1
        AGL_HT:5
        Blank:1
        AMSL_HT:5
        Blank:1
        Lighting:1
        Blank:1
        Horizontal_Accuracy:1
        Blank:1
        Vertical_Accuracy:1
        Blank:1
        Mark_Indicator:1
        Blank:1
        FAA_Study_Number:14
        Blank:1
        Action:1
        Blank:1
        Julian_Date:7
        Blank:1
        DATCHK_Code:6
        '
    }
);

my %hash_of_expanders = (
    AFF => {
        'AFF1' => '
            ',
        'AFF2' => '
',
        'AFF3' => '
',
        'AFF4' => '
'
    },
);

my %hash_of_geometry_creators = (
    OBSTACLE => {
        'OBSTACLE' => \&geometry_OBSTACLE_OBSTACLE,
    },
    APT => {
    'APT' => \&geometry_APT_APT,
    
    'RWY' => \&geometry_APT_RWY,
}
);

#connect to the database
my $dbfile = "./56day.db";
my $dbh = DBI->connect( "dbi:SQLite:dbname=$dbfile", "", "" );

#Set some parameters
# $dbh->do("PRAGMA page_size=4096");
$dbh->do("PRAGMA synchronous=OFF");

#Create base tables
my $create_metadata_table  = "CREATE TABLE android_metadata ( locale TEXT );";
my $insert_metadata_record = "INSERT INTO android_metadata VALUES ( 'en_US' );";

$dbh->do("DROP TABLE IF EXISTS android_metadata");
$dbh->do($create_metadata_table);
$dbh->do($insert_metadata_record);

#Load each data file in turn
foreach my $key ( sort keys %hash_of_parsers ) {

    #Open appropriate data file in the target directory
    my ( $filename, $dir, $ext ) = fileparse( $targetdir, qr/\.[^.]*/ );
    my $datafile = "$dir" . "$key.txt";
    my $baseFile = $key;

    my $file;
    open $file, '<', $datafile or die $!;

    #I'm trying a couple of different ways of looping through files
    #Read the entire file to an array
    # my $text = read_file($datafile);
    # my @lines = <$file>;
    # close($file);
    say "";

    while (<$file>) {

        # while ($text) {
        # for my $currentLineNumber (0 .. $#lines) {
        # print "$i: $x[$i]\n";
        # foreach (@lines) {
        my $textOfCurrentLine = $_;

        # my $textOfCurrentLine = $lines[$currentLineNumber];
        my $recordType;
        my $currentLineNumber = $.;

        # say $currentLineNumber;
        print "\rLoading $baseFile: # $currentLineNumber...";

        #Remove linefeed characters
        $textOfCurrentLine =~ s/\R//g;

        #Set up the recordType manually for files that don't follow the same format
        given ($baseFile) {
            when (/ARB|COM|HARFIX|NATFIX|SSD|STARDP|OBSTACLE/) {
                $recordType = $baseFile;
            }
            when (/WXL/) {
                $recordType = $baseFile;

                #BUG TODO Handle the oddball continuation records
                # if (trim( substr( $textOfCurrentLine, 0, 6 ) ) ~= m/)
            }
            when (/FSS/) {
                $recordType = $baseFile;

                #BUG TODO Handle the oddball continuation records
                # if (trim( substr( $textOfCurrentLine, 0, 6 ) ) ~= m/)
            }
            when (/AWOS/) {
                $recordType = trim( substr( $textOfCurrentLine, 0, 5 ) );
            }
            when (/AFF|ANR|ATS|AWY|FIX|HPF|ILS|MTR|NAV|PJA|PFR|TWR/) {
                $recordType = trim( substr( $textOfCurrentLine, 0, 4 ) );
            }
            when (/APT/) {
                $recordType = trim( substr( $textOfCurrentLine, 0, 3 ) );
            }
            when (/LID/) {
                $recordType = trim( substr( $textOfCurrentLine, 0, 1 ) );
            }
            default {
                die "I don't recognize $baseFile while reading $datafile";
            }

        }

        #Die if there is not a parse format for this input file and recordType
        die
          "$datafile line # $currentLineNumber : No parser defined for this recordType: $recordType"
          unless exists $hash_of_parsers{$baseFile}{$recordType};

        #Remove any spaces from the recordType
        $recordType =~ s/\s+//g;

        #Create an array to feed to Parse::FixedLength from the parser format we looked up in the hash_of_parsers
        my @parserArray =
          split( ' ', $hash_of_parsers{$baseFile}{$recordType} );

        #Create the specific parser for this recordType
        my $parser_specific =
          Parse::FixedLength->new( [@parserArray], \%parameters );

        #Check for mismatch between expected and actual lengths
        die "Line # $. - Bad parse for $recordType! Expected "
          . $parser_specific->length
          . " but read "
          . length($textOfCurrentLine) . "\n"
          unless $parser_specific->length == length($textOfCurrentLine);

        #Parse with specific parser
        my $data2 = $parser_specific->parse_newref($textOfCurrentLine);

        #Expand text if requested, may add columns to hash
        if ( exists $hash_of_expanders{$baseFile}{$recordType} ) {
        }

        #Create geometry if requested, may add columns to hash
        if ( exists $hash_of_geometry_creators{$baseFile}{$recordType} ) {

            #Call the appropriate subroutine with reference to our hash
            $hash_of_geometry_creators{$baseFile}{$recordType}->($data2);
        }

        #Create the table for each recordType if we haven't already
        #uses all the keys in the hash
        unless ( $haveCreatedTable{$baseFile}{$recordType} ) {

            #Makes a "CREATE TABLE" statement based on the keys of the hash
            my $drop = "DROP TABLE IF EXISTS " . $baseFile . "_" . $recordType;
            $dbh->do($drop);

            my $createStmt =
                'CREATE TABLE '
              . $baseFile . "_"
              . $recordType
              . '(_id INTEGER PRIMARY KEY AUTOINCREMENT,'
              . join( ',', keys $data2 ) . ')';

            # say $stmt;
            $dbh->do($createStmt);

            $haveCreatedTable{$baseFile}{$recordType} = 1;

            # #TODO Try preparing the sth here and only execute on outer loop
            # #Or would using prepare_cached work better?
            # my $insertStmt =
            # 'INSERT INTO '
            # . $baseFile . "_"
            # . $recordType . '('
            # . join( ',', keys $data2 )
            # . ') VALUES ('
            # . join( ',', ('?') x keys $data2 ) . ')';
            # my $sth = $dbh->prepare($insertStmt);
            # # say $sth;
            # $haveCreatedTable{$baseFile}{$recordType} = $sth;
            $haveCreatedTable{$baseFile}{$recordType} = 1;

            # print Dumper \%haveCreatedTable;

        }

        #-------------------
        #Make an "INSERT INTO" statement based on the keys and values of the hash
        my $stmt =
            'INSERT INTO '
          . $baseFile . "_"
          . $recordType . '('
          . join( ',', keys $data2 )
          . ') VALUES ('
          . join( ',', ('?') x keys $data2 ) . ')';

        # say $stmt;
        # $dbh->do( $stmt, undef, values $data2 );

        # say $stmt;
        # say values $data2;
        # print Dumper $data2;
        # # # Trying a cached version
        # my $sth = $dbh->prepare_cached($stmt);
        my $sth = $dbh->prepare($stmt);
        $sth->execute( values $data2 );

    }

}

sub coordinateToDecimalCifpFormat {

    #Convert a latitude or longitude in CIFP format to its decimal equivalent
    my ($coordinate) = shift;
    my ( $deg, $min, $sec, $signedDegrees, $declination, $secPostDecimal );
    my $data;

    #First parse the common information for a record to determine which more specific parser to use
    my $parser_latitude = Parse::FixedLength->new(
        [
            qw(
              Declination:1
              Degrees:2
              Minutes:2
              Seconds:2
              SecondsPostDecimal:2
              )
        ]
    );
    my $parser_longitude = Parse::FixedLength->new(
        [
            qw(
              Declination:1
              Degrees:3
              Minutes:2
              Seconds:2
              SecondsPostDecimal:2
              )
        ]
    );

    #Get the first character of the coordinate and parse accordingly
    $declination = substr( $coordinate, 0, 1 );

    given ($declination) {
        when (/[NS]/) {
            $data = $parser_latitude->parse_newref($coordinate);
            die "Bad input length on parser_latitude"
              if ( $parser_latitude->length != 9 );

            #Latitude is invalid if less than -90  or greater than 90
            # $signedDegrees = "" if ( abs($signedDegrees) > 90 );
        }
        when (/[EW]/) {
            $data = $parser_longitude->parse_newref($coordinate);
            die "Bad input length on parser_longitude"
              if ( $parser_longitude->length != 10 );

            #Longitude is invalid if less than -180 or greater than 180
            # $signedDegrees = "" if ( abs($signedDegrees) > 180 );
        }
        default {
            return -1;

        }
    }

    $declination    = $data->{Declination};
    $deg            = $data->{Degrees};
    $min            = $data->{Minutes};
    $sec            = $data->{Seconds};
    $secPostDecimal = $data->{SecondsPostDecimal};

    # print Dumper($data);

    $deg = $deg / 1;
    $min = $min / 60;

    #Concat the two portions of the seconds field with a decimal between
    $sec = ( $sec . "." . $secPostDecimal );

    # say "Sec: $sec";
    $sec           = ($sec) / 3600;
    $signedDegrees = ( $deg + $min + $sec );

    #Make coordinate negative if necessary
    if ( ( $declination eq "S" ) || ( $declination eq "W" ) ) {
        $signedDegrees = -($signedDegrees);
    }

    # say "Coordinate: $coordinate to $signedDegrees";           #if $debug;
    # say "Decl:$declination Deg: $deg, Min:$min, Sec:$sec";    #if $debug;

    return ($signedDegrees);
}

sub geometry_OBSTACLE_OBSTACLE {
    # my $hashRef = shift;
   
    my ( $hashRef ) =
      validate_pos(
        @_,
        { type => HASHREF }
      );
    
    #Calculate the decimal representation of lon/lat
    my $latitude = &coordinatetodecimal2(
        $hashRef->{Latitude_Degrees}, $hashRef->{Latitude_Minutes},
        $hashRef->{Latitude_Seconds}, $hashRef->{Latitude_Hemisphere},
    );
    my $longitude = &coordinatetodecimal2(
        $hashRef->{Longitude_Degrees}, $hashRef->{Longitude_Minutes},
        $hashRef->{Longitude_Seconds}, $hashRef->{Longitude_Hemisphere},
    );

    #and save in the hash as a POINT
    $hashRef->{Geometry} = "POINT(" . $longitude . " " . $latitude . ")";
}

sub geometry_APT_APT {
    # my $hashRef = shift;
   
    my ( $hashRef ) =
      validate_pos(
        @_,
        { type => HASHREF }
      );
    
   
    
    #Calculate the decimal representation of lon/lat
    my $latitude = &coordinatetodecimal(
        $hashRef->{AIRPORT_REFERENCE_POINT_LATITUDE_FORMATTED},
        );
    my $longitude = &coordinatetodecimal(
        $hashRef->{AIRPORT_REFERENCE_POINT_LONGITUDE_FORMATTED}
    );

    #and save in the hash as a POINT
    $hashRef->{Geometry} = "POINT(" . $longitude . " " . $latitude . ")";
}

sub geometry_APT_RWY {
    # my $hashRef = shift;
   
    my ( $hashRef ) =
      validate_pos(
        @_,
        { type => HASHREF }
      );
    
    
     
    
    #Calculate the decimal representation of lon/lat
    my $base_latitude = &coordinatetodecimal(
        $hashRef->{BASE_LATITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED}
    );
    my $base_longitude = &coordinatetodecimal(
        $hashRef->{BASE_LONGITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED}
    );

    my $reciprocal_latitude = &coordinatetodecimal(
        $hashRef->{RECIPROCAL_LATITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED}
    );
    my $reciprocal_longitude = &coordinatetodecimal(
        $hashRef->{RECIPROCAL_LONGITUDE_OF_PHYSICAL_RUNWAY_END_FORMATTED}
    );
    #and save in the hash as a POINT
    $hashRef->{Geometry} = "LINESTRING(" 
        . $base_longitude . " " . $base_latitude 
        . " , " 
        . $reciprocal_longitude . " " . $reciprocal_latitude
        . ")";
}